### ISSUE TITLE
javascript error: Cannot read property '$$testability' of undefined

### ISSUE THREAD

**Issue by roshnikhogta** [paul-hammant/ngWebDriver#100]
hi,
please check the site
https://eu.coresystems.net/workforce-management/#/login/
here there is no ng-app, i tired all the possible solution on net but not working. please help me

tried code
	WebDriverManager.chromedriver().setup();
		WebDriver driver = new ChromeDriver();
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		driver.get("https://eu.coresystems.net/workforce-management/#/login/");
		
		NgWebDriver ngDriver = new NgWebDriver((JavascriptExecutor) driver).withRootSelector("k-webkit k-webkit80");
		ngDriver.waitForAngularRequestsToFinish();
		Thread.sleep(5000);
		 driver.findElement(ByAngular.model("loginCtrl.loginInfo.accountName")).sendKeys("xyz");
	
i tried different withRootSelector but its not working. can yu please tell me the working code

**Comment by paul-hammant** [comment]
Yup, there's no root selector. I've not idea how to solve this. Can you ask the developers fot help?

**Comment by roshnikhogta** [comment]
ok, thanks paul. i had only this web site to get the hands on ngWebdriver. can you suggest me a good web site where i can get good hands on working with ngwebdriver

**Comment by paul-hammant** [comment]
I have not seen a tuturial
