### ISSUE TITLE
Determine if By is ByAngular

### ISSUE THREAD

**Issue by john-caleb-phillips** [paul-hammant/ngWebDriver#102]
A project I am working uses a mixture of Angular pages and non-Angular pages.  As a result I am using a mix of regular By [By.xpath(...), By.css(...), ...], and ByAngular [ByAngular.model(...), ByAngular.buttonText(...), ...].  

I need to do processing based on the type of locator, and it would be helpful If I could use instanceof to determine the type of the locator, similar to:
```java
if (locator instanceof ByAngular.BaseBy) {
    /* Do some angular specific processing */
} else {
   /* Do some non-angular specific processing */
}
driver.findElement(locator);
```

However, ByAngular.BaseBy is a protected class, and I cannot use it in the way demonstrated above. 
My current solution is as follows:
```java
if (isAngular(locator)) {
    /* Do some angular specific processing */
} else {
    /* Do some non-angular specific processing */
}
driver.findElement(locator);

...

private boolean isAngular(By locator) {
    return (locator instanceof ByAngularModel
        || locator instanceof ByAngularButtonText
        ...
    );
}
```
This works, but is not as readable as I would like.  Maybe BaseBy could be made public with a protected constructor?  Or is there another way I can achieve this?

**Comment by paul-hammant** [comment]
Release 1.1.6 should be what you want, John.
