### ISSUE TITLE
unable to click on the link test using ngWebdriver. The click did not work for me

### ISSUE THREAD

**Issue by Guruprasadraobk** [paul-hammant/ngWebDriver#103]
Hi Paul,

Could you please guide me to find "manage-roles" element in 2 different ways and then click on that element for an angular application using ngWebDriver

Below is the HTML:

< a _ngcontent-bkq-c4="" routerlink="manage-roles" ng-reflect-router-link="manage-roles" href="#/home/manage-roles" style="" xpath="1"> Roles< /a>

1) How to deal with "ng-reflect-router-link" and "_ngcontent" elements
2) How to find an element using its text (Similar to that in Xpath)
3) Is it possible to locate an element using its linktext (Similar to that in Xpath)

Your help is really appreciated. Thanks in advance

**Comment by paul-hammant** [comment]
see other comment

**Comment by Guruprasadraobk** [comment]
Thank you Paul. I will track the clarification in this ticket

Your comment: Just use regular WebDriver for that. XPath & attriubtes. ngWebDriver isn't needed for that

One more doubt I have:
1) What if I dont have "Roles" text by which I can select using normal webdriver text locator? How can I next do it using ngWebdriver
2) How to deal with "ng-reflect-router-link" and "_ngcontent" elements. How can I find elements under these attributes

Please guide, as I did not find right tutorial to handle this pattern.

**Comment by paul-hammant** [comment]
It is impossible to help you here. Ask a developer in your company to help you explore Selenium-WebDriver possibilities.

**Comment by Guruprasadraobk** [comment]
Thank you.
