### ISSUE TITLE
Finding tooltip text present under pre tag 

### ISSUE THREAD

**Issue by sandeepMannem** [paul-hammant/ngWebDriver#105]
I am trying to find the tooltip text present in our angular app. The tooltip is present under pre tag.
I tried all options with Selenium but dint work. Is it possible to fetch the text using NgWebdriver?
i cannot paste my dom elements here, as i work in secure environment.
```
<i` _ngcontent-jaq-c11 class=“tooltip ng-star-inserted”>
::before==$0
<pre _ngcontent-jaq-c11 class=“tooltiptext”>“Tool tip text”</pre>
</i>
```

**Comment by paul-hammant** [comment]
I don't know how to help you. I need more info.

Find the place on the page via a nearby widget. Move the mouse there to hover over the thing that would have the tool top. Then confirm it is in the DOM if that's what you want. Most of that is WebDriver not ngWebDriver.

**Comment by sandeepMannem** [comment]
We have ‘?’ In UI , if we mouseover on the icon its showing tooltip. If we inspect the icon its showing ::before element in DOM(you can see that element in the issue)The text present under pre tag.
 Tried to use action class but dint work.
Looking for help here.

**Comment by paul-hammant** [comment]
Still not enough info to help. Can you pair with someone in your company on this? There's nothing ngWebDriver specific here.

**Comment by sandeepMannem** [comment]
tried taking help from others but dint get any help. As this is Angular app i thought ngWebDriver has something that can help us.
Thanks for quick response
