### ISSUE TITLE
Callback method calling

### ISSUE THREAD

**Issue by dilhelh** [paul-hammant/ngWebDriver#107]
Is it the expected behavior to call the `waitForAngular2()` if the `hooks.$$testability` is stable or `hooks.$injector.get('$browser')` notifies when no outstanding requests?

https://github.com/paul-hammant/ngWebDriver/blob/8a85735daefb8893983d291a1d9520b4bd4430d8/src/main/resources/js/clientsidescripts.js#L152

https://github.com/paul-hammant/ngWebDriver/blob/8a85735daefb8893983d291a1d9520b4bd4430d8/src/main/resources/js/clientsidescripts.js#L154-L155

**Comment by paul-hammant** [comment]
I copied this file from Protractor.   See https://github.com/paul-hammant/ngWebDriver/blob/master/curl_clientsidescripts.sh

**Comment by dilhelh** [comment]
Do you know the best way to wait for `window.angular` to be available in an AngularJS application? Currently, at the beginning of waitForAngular1 there is some delay to get the angular object initialized in this site: https://www.advantageonlineshopping.com/#/

**Comment by dilhelh** [comment]
At this line:
https://github.com/paul-hammant/ngWebDriver/blob/8a85735daefb8893983d291a1d9520b4bd4430d8/src/main/resources/js/clientsidescripts.js#L145

The app is not considered an AngularJS app because `window.angular` initialization delay. So `ngWebDriver.waitForAngularRequestsToFinish()` seems that is not enough to wait the page get loaded

**Comment by dilhelh** [comment]
Hmmm so even if the page is in AngularJS, the Angular 2 callback must be executed too?
