### ISSUE TITLE
waitForAngularRequestsToFinish() not working as expected when window.angular is not initialized yet

### ISSUE THREAD

**Issue by dilhelh** [paul-hammant/ngWebDriver#108]
Do you know the best way to wait for `window.angular` to be available in an AngularJS application? Currently, at the beginning of `waitForAngular1` there is some delay to get the angular object initialized in this site: https://www.advantageonlineshopping.com/#/

At this line:
https://github.com/paul-hammant/ngWebDriver/blob/8a85735daefb8893983d291a1d9520b4bd4430d8/src/main/resources/js/clientsidescripts.js#L145

The app is not considered an AngularJS app because of `window.angular` initialization delay. So `ngWebDriver.waitForAngularRequestsToFinish()` seems that is not enough to wait the page get loaded.  What is the best approach to handle this situation?

**Comment by paul-hammant** [comment]
What site?

**Comment by dilhelh** [comment]
https://www.advantageonlineshopping.com/#/

**Comment by paul-hammant** [comment]
Angular's mounted on <body>. It should be easy enough.  Email me from your
advantageonlineshopping.com
<https://www.advantageonlineshopping.com/#/> account
so I know I'm not helping a hacker.

**Comment by dilhelh** [comment]
I am not a Hacker. I'm working on a mobile/web test framework that needs to use this project as a dependency. The site https://www.advantageonlineshopping.com is not maintained by my company but it is for test purpose only.

When I run these commands (from clientesidescripts.js):
![image](https://user-images.githubusercontent.com/33522742/110360426-76c59800-801d-11eb-8585-44b57c42687f.png)

I get undefined when running `tryEl(document.body)`. If body is the element that holds the angular, why we get undefined from method return?

**Comment by dilhelh** [comment]
Removing `injectorPlease` solved the problem. Not setting this argument in `getNg1Hooks()`

**Comment by paul-hammant** [comment]
The JavaScript is unchanged from the same file in Protractor. Have you found an enhancement to make the clientesidescripts.js file? If yes, then it should be contributed to the Protractor project.

**Comment by paul-hammant** [comment]
Happy customer :)
