### ISSUE TITLE
Cannot find elements on page with ngWebDriver

### ISSUE THREAD

**Issue by agatonovicmara** [paul-hammant/ngWebDriver#119]

**Comment by agatonovicmara** [comment]
I get "org.openqa.selenium.NoSuchElementException: searchText(Individual) didn't have any matching elements at this place in the DOM
"

**Comment by mrts** [comment]
@paul-hammant, I hijack this invalid issue for sending a big heartfelt thanks! We have an awesome [Selenide](https://selenide.org/)-based test harness that generally works well, but from time to time incomplete AJAX calls break some tests. `ngWebDriver.waitForAngularRequestsToFinish()` was a lifesaver for us!
