### ISSUE TITLE
Version 1.2.0 - Java 11 and later only?

### ISSUE THREAD

**Issue by desecheo** [paul-hammant/ngWebDriver#120]
Hello Paul, I was evaluating dependencies on a project and I noticed 1.2.0 is compiled for JDK 11. From what I read, Java 8 will still be around until 2026. Is your plan to skip JDK 8 support for this lib? Fine by me... I should probably move to JDK 17 already. A penny for your thoughts...

**Comment by paul-hammant** [comment]
See if you can downgrade it and keep all the tests passing. I mean in a
pull request

**Comment by desecheo** [comment]
Alright, I will give it a whirl.

**Comment by desecheo** [comment]
I guess you knew this :) but TestNG is already on JDK 11 and Jetty's support for JDK 8 is EOL. Thanks for keeping this super-useful lib updated.
