### ISSUE TITLE
NgWebDriver is not working for my project

### ISSUE THREAD

**Issue by gopalakannanp** [paul-hammant/ngWebDriver#122]
Hi @paul-hammant 

I am using selenium- java version 4.3.0 and testng 6.14.3 version.

I tried to use ngwebdriver latest version 1.1.5, It did not import ngwebdriver. But it is my maven depencies. Can you please help to resolve this issue?

<img width="681"
<img width="689" alt="Ng not import" src="https://user-images.githubusercontent.com/36475187/206444919-1369229f-1ea7-42ae-a35f-61f928a4d4b2.png">

<img width="681" alt="Ng Pom" src="https://user-images.githubusercontent.com/36475187/206445249-39976cf1-eab2-47fb-af31-767a1d831352.png">

**Comment by gopalakannanp** [comment]
Hi @paul-hammant 

I created a new project and tried it. Same issue. Sorry, I don't understand your previous comment. Can you help with this problem?

![image](https://user-images.githubusercontent.com/36475187/206455551-b7bdce0a-0a7d-46a8-9ccf-6d830bb12dd1.png)

![image](https://user-images.githubusercontent.com/36475187/206455595-83fd61b8-28fd-46be-a213-eece51d4e4bb.png)

**Comment by gopalakannanp** [comment]
Hi @paul-hammant 

Thanks for the clarification.

Here you go - https://github.com/gopalakannanp/ngwebdriver_new.git

Folder Location-> \ngwebdriver_new\src\main\java\org\example  -> Here I did not import NgWebDriver 

I included ngwebdriver maven dependencies in pom.xml file, But it did not work. 

Please advise.

**Comment by paul-hammant** [comment]
src/main/java classes cannot access <test> deps. Fixed in your codebase:

![image](https://user-images.githubusercontent.com/82182/206727793-abbfd3a6-4a40-4d65-80fe-40b6dd837fb3.png)

You should also upgrade to v1.2

**Comment by gopalakannanp** [comment]
Hi @paul-hammant 

Thanks for your help. It works perfectly after upgraded to v1.2.
