### ISSUE TITLE
No NgWebDriver class in maven build

### ISSUE THREAD

**Issue by kenshir007** [paul-hammant/ngWebDriver#17]
Greetings, I wonder should NgWebDriver class be in maven build, cause I can observe it in sources on GitHub?

**Comment by scottmboring** [comment]
The 0.9.4 build is a bad build and not inline with the documentation.

In addition to the NgWebDriver missing, the clientsidescripts.js is located in the wrong directory resulting in a FileNotFound exception.

    Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: src/main/resources/js/clientsidescripts.js (No such file or directory)

So the classes that do exist in the jar don't work such as WaitForAngularRequestsToFinish which for my needs is the most important feature.

**Comment by mattmfinn** [comment]
I'm having the same issue as well - and do not want to use a snapshot version.

**Comment by kenshir007** [comment]
Ive tried to use 0.9.5 by cloning sources and building jar but I would consider uploading 0.9.5 to mvn

**Comment by Dark3nz0** [comment]
When will 0.9.5 will be up on the central repo?

**Comment by manoj9788** [comment]
We have been busy with day jobs from vacations, I will investigate this issue shortly.
We will try to push 0.9.5 to central repo within this week.
CC: @paul-hammant

**Comment by kenshir007** [comment]
Thank you for hard working) You guys are doing great job

**Comment by J-JRC** [comment]
Hello any update on this issue?

**Comment by supreetsingh26** [comment]
Hi, It will be really helpful to have the fix of this issue in the new version. Or if there is some alternate then please share?
cc: @manoj9788, @paul-hammant

**Comment by sklegg** [comment]
I just ran into this, too.

**Comment by paul-hammant** [comment]
I'll try to get to this in the next couple of days, folks.

**Comment by paul-hammant** [comment]
0.9.5 released

**Comment by manoj9788** [comment]
Cool. Thanks Paul.
