### ISSUE TITLE
Execute scope function

### ISSUE THREAD

**Issue by MotherCake** [paul-hammant/ngWebDriver#22]
Hi

i try to execute a scope function in my test class. On my GUI there is a link
`<a data-target="#" ng-click="logout()">logout</a>`

How can I execute the logout function within my test class? Thats not work, but something like this?
`driver.findElement(ByAngular.model("logout")).click();`

**Comment by manoj9788** [comment]
@MotherCake you can't use ByAngular.model for a ng-click directive. You will have to work out with other locator strategy. ng-click is not available in Protractor too.

**Comment by MotherCake** [comment]
Hi manoj9788

thx for your reply.

**Comment by manoj9788** [comment]
Nw... closing this.
