### ISSUE TITLE
Support for Angular 2

### ISSUE THREAD

**Issue by jleeh** [paul-hammant/ngWebDriver#25]
Hi,

I'm currently investigating supporting Angular 2 applications, we use your library to currently, but there doesn't seem to be any support for Angular 2?

I've seen that there's client side js 'waitForAllAngular2' which is the async call to wait for the Angular 2 JS page to construct, but there's no method in the class NgWebDriver to support it.

Would it be possible to gain support for Angular 2?

Thanks

**Comment by paul-hammant** [comment]
Pull requests accepted :)

**Comment by paul-hammant** [comment]
I started the work - try out `NgWebDriver.waitForAngular2RequestsToFinish()`

**Comment by roydekleijn** [comment]
Using Angular 1 we had the option to enable debug info and reveal the binding names, with:  angular.reloadWithDebugInfo(); (run from the console tab)


What kind of option do we have with Angular2 ?
