### ISSUE TITLE
Regarding driver.get

### ISSUE THREAD

**Issue by Amrit998** [paul-hammant/ngWebDriver#27]
Hello, I was trying to learn protactor testing using ng webdriver, but in your code sometimes you have use localhost in driver.get,which my machine cant open because its  your machine can access only , if you can give the url , just like you have use in some test cases ,it will be great help for me..

**Comment by Amrit998** [comment]
Really your work is amazing

**Comment by paul-hammant** [comment]
I'm not sure what you're asking - can you help me reproduce this - a code snippet for example?

**Comment by Amrit998** [comment]
Thanks for replying,Earlier when i was trying to learn i was facing some issues but now i have managed that.

**Comment by paul-hammant** [comment]
no probs - have fun with Selenium and ngWebDriver :)
