### ISSUE TITLE
waitForAngularRequestsToFinish() is working intermittently in chrome version 47.0.25

### ISSUE THREAD

**Issue by anand-sn** [paul-hammant/ngWebDriver#29]
As my application is based on angularJS, i am using the ngwebdriver's method waitForAngularRequestsToFinish to handle the background rendering to complete. 
(Webdriver's method of implicit and explicit wait is not working properly on AngularJS application)

Issue is that when I ran the script yesterday, e2e automation flow was working fine. But, today the script fails as waitForAngularRequestsToFinish is not able to handle the rendering.

Please guide how to handle the above issue.

snippet of my code to execute the browser driver:

```
public static void callChrome()
	{
		System.setProperty("webdriver.chrome.driver", "D:\\software_setup\\chromedriver.exe");
		
	}
	
	//public static WebDriver driver=new FirefoxDriver(FFprofile());
	public static WebDriver driver=new ChromeDriver();
	public static NgWebDriver ngwebdriver=new NgWebDriver((JavascriptExecutor)driver);

```

**Comment by paul-hammant** [comment]
v0.9.7 has been released with a newer WebDriver dependency (2.53.1) - see if that is better.  Perhaps also help me out with example code **and a target website** that exhibits the problem. Lastly, your OS version too.

**Comment by anand-sn** [comment]
Hi Paul, 
As mentioned in the above comment, I updated the POM.xml file

```
<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.1</version>
</dependency>

<dependency>
		<groupId>com.paulhammant</groupId>
		<artifactId>ngwebdriver</artifactId>
		<version>0.9.7</version>
		<scope>test</scope>
</dependency>	
		
```

Chrome Version - Version 47.0.2526.106 m
OS - Window 7.

Currently, script is not executing properly and fails at waitForAngularRequestsToFinish().

Please suggest the solution.

**Comment by paul-hammant** [comment]
Perhaps also help me out with **example code and a target website** that exhibits the problem
