### ISSUE TITLE
find element By Binding is not working

### ISSUE THREAD

**Issue by uparejiya** [paul-hammant/ngWebDriver#30]
I am facing this issue from last 3 days. I am trying to automate https://weather.com/en-IN webapplication which built in AngularJS. 

I am trying to find element using binding but its giving me like no such element is there in DOM.
Below is the test scenario:

ChromeDriver driver = new ChromeDriver();
		NgWebDriver ngWebDriver = new NgWebDriver(driver);
driver.get("https://weather.com/en-IN");
ngWebDriver.waitForAngularRequestsToFinish();
WebElement menuEle = driver.findElement(ByAngular.binding("::userLocationVm.localeDisplay"));

Please help me out for this issue.

**Comment by paul-hammant** [comment]
I will take a look ...

**Comment by uparejiya** [comment]
@paul-hammant  any update on this ?

**Comment by paul-hammant** [comment]
https://weather.com/en-IN isn't compatible. Weird page. Loads of errors.
