### ISSUE TITLE
findElements() is meaningless

### ISSUE THREAD

**Issue by phystem** [paul-hammant/ngWebDriver#31]
> This locator zooms in on a single cell, findElements() is meaningless

Is there any specific reason why `findElements` is not implemented for `ByAngularRepeaterCell` and `ByAngularRepeaterRow`

I needed it in my application

**Comment by manoj9788** [comment]
You are very welcomed to submit a PR

**Comment by paul-hammant** [comment]
As Manoj says, pull-requests welcome :)

**Comment by paul-hammant** [comment]
The singular version uses findRepeaterElement() in clientsidescripts.js https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js#L339 

There's no plural version.
