### ISSUE TITLE
Problem in initialization NgWebDriver

### ISSUE THREAD

**Issue by njauhari** [paul-hammant/ngWebDriver#33]
Hi,

I am facing problem (compile time) at the time of NgWebDriver initialization using below code.

private NgWebDriver ngWebDriver;
private WebDriver selenium;

selenium = new FirefoxDriver;
ngWebDriver = new NgWebDriver(selenium);

using above code, I am getting compile time error --> 
The constructor NgWebDriver(WebDriver) is undefined

I know this can be fixed using the FirefoxDriver instead of WebDriver but i have a situation where I need to use WebDriver.

Thanks,
Nikesh

**Comment by sunnysachdeva** [comment]
I use below code
ngWebDriver = new NgWebDriver((JavascriptExecutor) selenium);

**Comment by paul-hammant** [comment]
As sunnysachdeva says. Closing.
