### ISSUE TITLE
NullPointerException when using angular repeater with HtmlUnitDriver

### ISSUE THREAD

**Issue by vivienmast** [paul-hammant/ngWebDriver#34]
When using the ngWebDriver with the HtmlUnitDriver (Selenium's headless browser driver), I have not been able to successfully use the angular repeater. The following code will lead to a NullPointerException:

```
String ANGULAR_REPEATER = "some angular repeater";
WebDriver driver = new HtmlUnitDriver(true);
ngWebDriver = new NgWebDriver((JavascriptExecutor) driver);
driver.get(URL);
WebElement element = driver.findElement(ByAngular.repeater(ANGULAR_REPEATER).row(0));
```

Apparently, the reason is that for the vararg in
public Object executeScript(String script, final Object... args)
in HtmlUnitDriver, ngWebdriver sends a single null-Argument that later causes a null-PointerException.

I assume the simple solution would be to simply call the method with no arguments, thus preventing the NullPointerException, but maybe there is a reason for sending this null-argument?

I would also be happy to learn about a workaround that lets me use the angular repeater with HtmlUnitDriver until the issue is solved.

**Comment by manoj9788** [comment]
We haven't tested our code using HtmlUnitDriver (at least I), so probably the first case we see.

**Comment by paul-hammant** [comment]
We're not going to support HtmlUnitDriver. Try https://github.com/detro/ghostdriver instead.

**Comment by vivienmast** [comment]
Thanks for the info, I will try Ghostdriver.
