### ISSUE TITLE
package com.paulhammant.ngwebdriver does not exist

### ISSUE THREAD

**Issue by meettejender** [paul-hammant/ngWebDriver#38]
I am using Maven and configured it to get ngwebdriver-0.9.7.jar. The imports statements for ngwebdriver throw error at compile time. This happens if i use these import statements in my cucumber step definition files. I have verified existence of the ngwebdriver-0.9.7 under Maven Dependencies.

I have created another project without cucumber references and it works when i use ngWebdriver in testNG class without cucumber.

import com.paulhammant.ngwebdriver.ByAngular;
import com.paulhammant.ngwebdriver.NgWebDriver;

NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor)driver);
driver.get("https://angularjs.org/");
ngWebDriver.waitForAngularRequestsToFinish();
driver.findElement(ByAngular.model("yourName")).sendKeys("Bill");
 
Please advise.

**Comment by in026hoe** [comment]
I am having the same problem. 

By any chance; do you also use selenium? I suspect that this issue arises when using selenium 3.0(.1) as I have a new project in 3.0.1 where this issue exists, but another old project in selenium 2.53.1 works fine.

P.S. I am using ngWebDriver version 0.9.6

**Comment by paul-hammant** [comment]
ngWebDriver 0.9.9 pushed - that deps on Se3.0.1

**Comment by surajkakode** [comment]
This is happening again in 1.1.3

**Comment by paul-hammant** [comment]
"package com.paulhammant.ngwebdriver does not exist" in 1.1.3??  Looks OK to me:

```
 wget http://central.maven.org/maven2/com/paulhammant/ngwebdriver/1.1.3/ngwebdriver-1.1.3.jar
...
$ jar -tvf ngwebdriver-1.1.3.jar 
     0 Wed Apr 18 09:23:32 BST 2018 META-INF/
   130 Wed Apr 18 09:23:30 BST 2018 META-INF/MANIFEST.MF
     0 Wed Apr 18 09:23:04 BST 2018 js/
     0 Wed Apr 18 09:23:06 BST 2018 com/
     0 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/
     0 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/
 31485 Wed Apr 18 09:23:04 BST 2018 js/clientsidescripts.js
  2957 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterCell.class
  1104 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterRow$NgFindByBuilder.class
   916 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterColumn$FindBy.class
  2135 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularModel.class
  2362 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngular$BaseBy.class
  1005 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularModel$NgFindByBuilder.class
   926 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterCell$FindBy.class
  1089 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularPartialButtonText$NgFindByBuilder.class
  3121 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterRow.class
  2191 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularPartialButtonText.class
  3003 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeater.class
   841 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularBinding$FindBy.class
   859 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularButtonText$FindBy.class
  5590 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngular.class
  1019 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularOptions$NgFindByBuilder.class
  1130 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularCssContainingText$NgFindByBuilder.class
  1054 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularExactBinding$NgFindByBuilder.class
  1057 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeater$NgFindByBuilder.class
  2294 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularCssContainingText.class
   829 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularModel$FindBy.class
  2142 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularButtonText.class
   916 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularCssContainingText$FindBy.class
  1040 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularButtonText$NgFindByBuilder.class
  4138 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/NgWebDriver.class
   871 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularExactBinding$FindBy.class
  1019 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularBinding$NgFindByBuilder.class
   904 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterRow$FindBy.class
  2850 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterColumn.class
  2112 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularOptions.class
   841 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularOptions$FindBy.class
  1153 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterCell$NgFindByBuilder.class
   901 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularPartialButtonText$FindBy.class
  2177 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularBinding.class
  1136 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeaterColumn$NgFindByBuilder.class
  2607 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngular$Factory.class
   869 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularRepeater$FindBy.class
  2220 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/ByAngularExactBinding.class
   444 Wed Apr 18 09:23:06 BST 2018 com/paulhammant/ngwebdriver/VariableNotInScopeException.class
     0 Wed Apr 18 09:23:32 BST 2018 META-INF/maven/
     0 Wed Apr 18 09:23:32 BST 2018 META-INF/maven/com.paulhammant/
     0 Wed Apr 18 09:23:32 BST 2018 META-INF/maven/com.paulhammant/ngwebdriver/
  2849 Wed Apr 18 09:22:58 BST 2018 META-INF/maven/com.paulhammant/ngwebdriver/pom.xml
   111 Wed Apr 18 09:23:32 BST 2018 META-INF/maven/com.paulhammant/ngwebdriver/pom.properties
```

**Comment by paul-hammant** [comment]
I'm going to ask you to be more polite, Suraj.

Looks like an Intellij screenshot. Can you check this artifact by hand - http://central.maven.org/maven2/com/paulhammant/ngwebdriver/1.1.3/ngwebdriver-1.1.3.jar

Do you have anyone local to you in EPAM or is it Cap Gemini? who can help you track towards root cause?  Can you try going back to 1.1.2 to see what happens?  Then forwards again to 1.1.3. Then forwards again to 1.1.4?  How about closing Intellij and reopening?  What does the Maven script "mvn clean install" say from the command line when you run it?

**Comment by pavannarrasdet** [comment]
Suraj , you need to remove scope tag in Pom for test .. if you are keeping
scripts under main module
Please check your Pom model

**Comment by pavannarrasdet** [comment]
Hey Paul,
What’s new things in 1.1.4 , am using 1.1.2
Do I have any benefits if I forward it ?

**Comment by pavannarrasdet** [comment]
@Paul,
Looks like 1.1.4 is not yet pushed in repo? I could use up to 1.1.3 ? When
I kept 1.1.4 in my Pom.xml it’s givig unable to read artificial id in my
pom.xml file
Just heads up

**Comment by dantran** [comment]
@pavannarrasdet   https://github.com/paul-hammant/ngWebDriver/blob/master/Code-Of-Conduct.md :-)

**Comment by garimagoyal217** [comment]
I am using ngwebdriver version 1.1.3 and selenium version 3.5.3 in maven dependency but getting the error while running the code through mvn command: error: package com.paulhammant.ngwebdriver does not exist. However, I am not getting any error in my eclipse project.
Please help.

**Comment by paul-hammant** [comment]
Upload a reproduction to Github please, Garima.  Maven build file, src could be a single JUnit test that would use Selenium and ngWebDriver together to hit say Google.com for something ............. that then fails because of this "package com.paulhammant.ngwebdriver does not exist" error.

**Comment by garimagoyal217** [comment]
Hi 

Compilation error is gone when I commented the <scope> tag from dependency.
<dependency>
  		<groupId>com.paulhammant</groupId>
  		<artifactId>ngwebdriver</artifactId>
  		<version>1.1.3</version>
  		
	</dependency>

Thanks
garima

**Comment by paul-hammant** [comment]
Cool :)

**Comment by PrasadNutalapati** [comment]
Hello Friends !
I am using ngWebDriver in a Cucumber-Serenity JVM project.
Even after commenting the scope as 'test' in the pom file, I am getting the compilation error. 
package com.paulhammant.ngwebdriver does not exist.
I ran "mvn clean install" and maven --> update project in Eclipse IDE. also.
