### ISSUE TITLE
Get Button in repeater

### ISSUE THREAD

**Issue by MotherCake** [paul-hammant/ngWebDriver#39]
Hi

i want to click on a button within a repeater. HTML looks like 
```
<tr ng-repeat="element in elements">
    <td>{{element.value1}}</td>
    <td>{{element.value2}}</td>
    <td>
        <button class="btn btn-green" type="button" data-toggle="modal" ng-click="element.function">
        </button>
    </td>
</tr>
```
How can i get the Button Element?

**Comment by paul-hammant** [comment]
webDriver.findElements(ByAngular.repeater("element in elements")).get(n).findElement(By.tagName("button")).click();

or

webDriver.findElement(ByAngular.repeater("element in elements").row(n)).findElement(By.tagName("button")).click();
