### ISSUE TITLE
how can I find an element  used repeater in repeater (Java)

### ISSUE THREAD

**Issue by kent-zhu** [paul-hammant/ngWebDriver#4]
Hi Paul,

    I have one question about how to find an element repeater in repeater? below is the angular code, I'm trying to find the first element under month 2014-01(or a dynamic month ), so Only can I use the function like
   driver.findElements(ng.repeater("order in orderListData['2014-01']").row(0))?

and sometime it even could not find this element. 

So It there any dynamic way to solve this issue?

<div class="list disable-user-behavior" ng-transclude="" ng-class="{'list-editing': showDelete, 'list-reordering': showReorder}" ng-repeat="month in orders">
   <div class="item item-divider ng-binding">2014-01</div>
   <a class="item item-icon-left disable-user-behavior" ng-repeat="order in       orderListData[month]" ng-click="goToDetail(object)">
      <span class="item-note ng-binding">Error</span>
      <i class="icon icon-buy"></i>
     <span class="ng-binding" ng-bind-html="html">
   </a>
   <a class="item item-icon-left disable-user-behavior" ng-repeat="order in    orderListData[month]" ng-click="goToDetail(object)">
          <span class="item-note ng-binding">Filled</span>
          <i class="icon icon-buy"></i>
          <span class="ng-binding" ng-bind-html="html">
     </a>
</div>
 <div class="list disable-user-behavior" ng-transclude="" ng-class="{'list-editing':   showDelete, 'list-reordering': showReorder}" ng-repeat="month in orders">
     <div class="item item-divider ng-binding">2013-12</div>
    <a class="item item-icon-left disable-user-behavior" ng-repeat="order in   orderListData[month]" ng-click="goToDetail(object)">
     <span class="item-note ng-binding">Cancelled</span>
     <i class="icon icon-buy"></i>
     <span class="ng-binding" ng-bind-html="html">
  </a>
</div>

Thanks 
Kent

**Comment by manoj9788** [comment]
Hi Paul, I think we should close this as well.

**Comment by paul-hammant** [comment]
JavaScript for repeater update - in the next release
