### ISSUE TITLE
getLocationAbsUrl(); not working after upgrade to 1.0

### ISSUE THREAD

**Issue by borisivan** [paul-hammant/ngWebDriver#40]
Hi,

After upgrading to 1.0, I find that getLocationAbsUrl(); yields the following below. Worked previously in 0.9.6. Did something break, or maybe the usage changed?

org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined
(Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
...
...
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Session ID: 9b7d0e1e-7ee0-4da2-938e-30fefc7052eb
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)
	at com.paulhammant.ngwebdriver.NgWebDriver.getLocationAbsUrl(NgWebDriver.java:81)

**Comment by paul-hammant** [comment]
OK - a test should have caught that in the ngWebDriver build - the JS script that does the work is slurped from the protactor repo. I'll work on this at the w/e.

**Comment by borisivan** [comment]
Thanks. I am new to both ngWebDriver and protractor in general, so hopefully it's not due to user error. The URL was correctly retrieved with 0.9.6, when pointed to the same page though, when calling getLocationAbsUrl.

For what it's worth, I also received the "Cannot read property '$$testability'" error in a couple of other methods as well (even though other ones were working fine), so if you find root cause re: why it happens in getLocationAbsUrl, you may find that it applies to more than method.. if you need more info on that I can try and find an example.

**Comment by paul-hammant** [comment]
Yeah, I might need help with a reproduction. I thought there might not be a test for that method, but there is - https://github.com/paul-hammant/ngWebDriver/blob/master/src/test/java/com/paulhammant/ngwebdriver/AngularAndWebDriverTest.java#L715

Can you clone this repo, crank up intellij and run that test on it's own?  Then morph it to point at your site ?

**Comment by ph-ms** [comment]
@borisivan Is your app AngularJS or Angular (2+) ?

**Comment by borisivan** [comment]
Hi, sorry for the delay. AngularJS, 1.6 I think.

**Comment by paul-hammant** [comment]
Is it possible for you to give me a reproduction?

**Comment by borisivan** [comment]
I tried to acquire 1.1-SNAPSHOT, but it doesn't seem to be available in any maven repos. Should I use 1.0?

**Comment by ph-ms** [comment]
Build it yourself after cloning. It's a Maven project and doesn't take long. Do -DskipTests if you want to make it faster.

**Comment by borisivan** [comment]
OK, I'll give that a shot. In the meantime, I've reproduced the same problem as described above, If there is a debug image I can run that might yield additional info, I'd be happy to. Unfortunately I can't point you to a webpage, this isn't publicly accessible, etc.

In the following code sequence:

public static List<WebElement> repeatedElements;
...
...
String absoluteUrl = ngWebDriver.getLocationAbsUrl();
repeatedElements = webDriver.findElements(ByAngular.repeater(myString));

In ngwebdriver 0.9.7, both lines of code work.

In ngwebdriver 1.0, I get the error described above on the getLocationAbsUrl() call... but findElements(ByAngular.repeater....) still works fine.

I'm using Selenium 2.53.1.

**Comment by borisivan** [comment]
Looking at the commits, the only change from 1.0 to 1.1-SNAPSHOT is a change to the pom file for selenium 3.3 support, so I probably don't need 1.1-SNAPSHOT. Let me know what addl data I can provide re: reproducing in 1.0.

**Comment by ph-ms** [comment]
the master of ngWebDriver builds against Selenium 3.3, for what it is worth. I've not released that because no code changes were necessary vs 3.0.1

**Comment by borisivan** [comment]
The problem is the change between ngwebdriver 0.9.6 to 0.9.7, sorry if I was misleading re: 1.0.

0.9.7 (and 1.0) fails, 0.9.6 succeeds. The following will reproduce the problem with 0.9.7, but will succeed with 0.9.6:

public NgWebDriver ngWebDriver;
private ChromeDriver driverc;

...
driverc = new ChromeDriver();
driverc.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
ngWebDriver = new NgWebDriver(driverc);
driverc.get("https://angularjs.org/");
Thread.sleep(15000);
String absoluteUrl = ngWebDriver.getLocationAbsUrl();

absoluteURL will be set to "\" with 0.9.6, but will produce the exception regarding "$$testability" with 1.0, and a similar error (but worded differently) in 0.9.7.

**Comment by borisivan** [comment]
Problem seems to revolve around me not using withRootSelector. Started looking at that and seems like that might be working now. If you also feel that probably explains things based on my previous descriptions above, then please do feel free to close the issue. Thanks.

**Comment by ph-ms** [comment]
Good to know. I should still put something in the page - to help the next person who encounters it.

**Comment by paul-hammant** [comment]
Readers: Specifying rootSelector probably solved it for the OP
