### ISSUE TITLE
ngWebDriver with Javascript or node.js  npm module?

### ISSUE THREAD

**Issue by rchovatiya88** [paul-hammant/ngWebDriver#42]
Hi paul, 
Thank you soo much for creating ngWebDriver, in my previous project we had an angularjs application, It worked out perfectly with JAVA based developers we just imported ngWebDriver to find elements.. but now more and more organization are moving towards node.js and javascript, ProtractorTest is there but as a testing framework its just not stable. i have been using nightwatch.js which is great for non-angular websites but for angular due to elements and angular animation i'm afraid i'll have to add plenty of waits.. Honestly i'm not sure how much effort it would be create javascript based APIs. Anyways. Thanks a lot!

**Comment by paul-hammant** [comment]
Really ngWebDriver is just a Java wrapper for the JavaScript technology from the Protracter team. There's literally nothing I could do better than that team for Node.js developers - sorry!
