### ISSUE TITLE
Can NgWebDriver work with Selenium RemoteWebDriver?

### ISSUE THREAD

**Issue by Neal910** [paul-hammant/ngWebDriver#47]
## Backgroud: 
My testing automation is using selenium grid, so I initialize RemoteWebDriver instance every time when selenium starts to run. I also use CDI to inject each remote webdriver to page object, but I don't think it's matter for this question. 

## Question:
I am wondering if I can initialize ngWebDriver with the driver passed by RemoteWebDriver.

For example:
`WebDriver lWebDriver = null;`
`lWebDriver = new RemoteWebDriver(new URL(GRID_HUB_URL), getWebDriverCapability());`     
`...  `     
`new NgWebDriver(lWebDriver ).waitForAngularRequestsToFinish(); `

**Comment by paul-hammant** [comment]
You tell me: What happens when you run that?

**Comment by jippeholwerda** [comment]
We have just tried the exact same scenario. Running `ngWebDriver.waitForAngular2RequestsToFinish()` results in an exception: 

    org.openqa.selenium.ScriptTimeoutException: asynchronous script timeout: result was not received in 30 seconds

Looking in the debugger at which async script actually is being executed you can see that looking up `waitForAllAngular2` fails:

    var callback = arguments[arguments.length - 1];\n\nnull

**Comment by RusmanCool** [comment]
For me waitForAngularRequestsToFinish is working even for Angular2.

-----Original Message-----

**Comment by jippeholwerda** [comment]
You're right, `waitForAngularRequestsToFinish` indeed does work, even for Angular 4.

**Comment by manoj9788** [comment]
Should we just close this? ... Alright Closing it...
Let me know if a re-open is required.

**Comment by Neal910** [comment]
Hi @jippeholwerda @RusmanCool , thanks for answer. I didn't get chance to really test it recently. I just want to confirm that the driver you use to initialize ngWebDriver is from selenium grid remote driver? Thanks a lot.

**Comment by jippeholwerda** [comment]
Yep, I use the RemoteWebdriver.

**Comment by RusmanCool** [comment]
Make sure pass the tag name of the Angular root element in your app during ngWebdriver initialization, as if it is not a default tag then nothing will work with ngWebdriver.
As far as the driver - any instance of a WebDriver will work, local or remote.

-----Original Message-----

**Comment by Neal910** [comment]
Hi guys,
Seems I have to cast my driver to JavascriptExcutor like below:
`NgWebDriver lNgWebDriver = new NgWebDriver((JavascriptExecutor) iDriver);`
`lNgWebDriver.waitForAngularRequestsToFinish();`
But I am having trouble with cast "org.openqa.selenium.SearchContext$WebDriver$1968860532$Proxy$_$$_WeldClientProxy cannot be cast to org.openqa.selenium.JavascriptExecutor"

Is there way that I don't have to cast to JavascriptExcutor like below:
`NgWebDriver lNgWebDriver = new NgWebDriver( iDriver);`
`lNgWebDriver.waitForAngularRequestsToFinish();`

Thanks a lot.

**Comment by paul-hammant** [comment]
You sure this is not a Weld issue?  

WebDriver has many fine grained interfaces - see here - https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java

Are you registering WebDriver or RemoteWebDriver as the type for the implementation?

**Comment by Neal910** [comment]
Yes, you are right, my bad. Just got a solution to get around of casting. Thanks again.
