### ISSUE TITLE
ng-binding

### ISSUE THREAD

**Issue by Moshik177** [paul-hammant/ngWebDriver#48]
Hi Paul ,

i try to use your library but it's not working on ng-bind i am getting the error : 
TypeError: getNg1Hooks(...) is undefined

when i try to find the element like that : 
ngWebDriver = new NgWebDriver((JavascriptExecutor) driver);
ngWebDriver.waitForAngularRequestsToFinish();
WebElement firstname = driver.findElement(ByAngular.exactBinding("d.name"));

the element in the page look like that :
>div class="" ng-show="analyticsDashboard.pageData.name"<
>div id="dashboard-top" class="dashboard-print"<
>ul class="nav nav-tabs"<

>li class="active" ng-repeat="d in analyticsDashboard.pageData.dashboards" ng-class="{active:d.token == analyticsDashboard.dashboardName}"<
>a ng-bind="d.name" ng-click="analyticsDashboard.changeDashboard(d)">Content Transfer</a<

thanks!

**Comment by paul-hammant** [comment]
Can you reproduce the problem with a website that is in public ?

**Comment by Moshik177** [comment]
it's a problem ,
i understand the problem but i don't think that i have the solution yet , the d.name that i am looking is a javascript parameter  ( the ng-repeat get the d parameter from the analyticsDashboard.pageData.dashboards ) and i searched the string d.name ,instead of the value of d.name , there is a way to get the value of the d.name?

**Comment by RusmanCool** [comment]
First, is your root Angular element default one or something else. Check ReadMe file about that.
Second, also check in the ReadMe what commands are not working with Angular 2.

-----Original Message-----

**Comment by Moshik177** [comment]
Hi RusmanCool,
as i understood from reading over the network ng.bind or ng.model are commands that i supposed to set a javascript parameters but when i did that i am getting the stucktrace:
org.openqa.selenium.JavascriptException: TypeError: getNg1Hooks(...) is undefined
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'PC-9324PT', ip: '192.168.40.171', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\moshikk\AppData\Local\Temp\rust_mozprofile.E0Dyxy9O4T2u, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0.1, platformVersion=6.1, moz:processID=13472.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 13b2f8d5-66f5-4b57-a526-55f5cebdad62

what can we do about it ?

**Comment by AsifIquebal** [comment]
Hi Paul,
Getting 
TypeError: getNg1Hooks(...) is undefined,
Sample code; 
`
    WebDriver driver;
    NgWebDriver ngWebDriver;
    @Test
    public void test2(){
        System.setProperty("webdriver.gecko.driver","src/main/resources/drivers/geckodriver.exe");
        driver = new FirefoxDriver();
        ngWebDriver = new NgWebDriver((JavascriptExecutor) driver);
        driver.get("https://angularjs.org/");
        ngWebDriver.waitForAngularRequestsToFinish();
        driver.findElement(ByAngular.model("yourName")).sendKeys("Test");
        System.out.println(driver.findElement(By.xpath("//h1[@class='ng-binding']")).getText());
    }
`
[finding by model is causing this issue]
driver.findElement(ByAngular.model("yourName")).sendKeys("Test");
Using selenium 3.5.3, Java 1.8, ngwebdriver 1.0

**Comment by paul-hammant** [comment]
I think ngWebDriver can't find the rectangle that has Angular in it.  Have a quick look at https://github.com/paul-hammant/ngWebDriver/#helping-ngwebdriver-find-angular-apps-in-a-page and see if you should be using `withRootSelector(..)` somehow.

**Comment by paul-hammant** [comment]
I think this was solved by rootSelector - closing because of lack of response

**Comment by dwi-di** [comment]
ran into the same issue but the rootSelector was correct. Found this on the [angular.bootstrap](https://docs.angularjs.org/api/ng/function/angular.bootstrap) docs:

> Note: Do not bootstrap the app on an element with a directive that uses transclusion, such as ngIf, ngInclude and ngView. Doing this misplaces the app $rootElement and the app's injector, causing animations to stop working and making the injector inaccessible from outside the app. 

My ng-app looked like this:
`<div g-app="MyApp" ng-view></div>`

After changing it to this, everthing works:
`<div ng-app="MyApp"><div ng-view></div></div>`

@paul-hammant perhaps you want to add this to the readme?

**Comment by paul-hammant** [comment]
Could do yes. I'm happy to consume pull-requests too :)
