### ISSUE TITLE
AngularAndWebDriverTest.java needs update

### ISSUE THREAD

**Issue by zaphinath** [paul-hammant/ngWebDriver#5]
ngModel.mutate(we, "location.City", "'Narnia'"); line 187

On the example webpage you are using there is no location.City model or variable. I am not sure if I am missing something or if their website has changed.

**Comment by manoj9788** [comment]
Paul, I think we can close this now. Its updated and working fine.

**Comment by paul-hammant** [comment]
Fixed as suggested
