### ISSUE TITLE
ngWebDriver showing unexpected exceptions

### ISSUE THREAD

**Issue by venkat6080** [paul-hammant/ngWebDriver#50]
Hi,
*When i am using ngWebDriver at ng -model we are getting this error "org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined". Why these error showing i dont know.

*But when we are using Web Driver it working fine.

*I am sharing my code for reference purpose. Could u please check it

**Code::**

package angularJS;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import com.paulhammant.ngwebdriver.ByAngular;
import com.paulhammant.ngwebdriver.NgWebDriver;

public class Test1 {
	public static WebDriver driver ;
	public static NgWebDriver ngdriver;

	@BeforeClass
	public static void open()
	{
		System.setProperty("webdriver.chrome.driver", ".\\Drivers\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://angularjs.org/");	
	}
	@Test
	public static void get_Message()
	{
		ngdriver = new NgWebDriver((JavascriptExecutor) driver);
		ngdriver.waitForAngularRequestsToFinish();
		WebElement element = driver.findElement(ByAngular.model("yourName"));//.sendKeys("Data Name");
		element.sendKeys("venkat hi");
		String actual = driver.findElement(By.xpath("//h1[@class='ng-binding']")).getText();
		System.out.println("The name is "+actual);
	}
}

**Error:**
org.openqa.selenium.WebDriverException: unknown error: Cannot read property '$$testability' of undefined
  (Session info: chrome=62.0.3202.89)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

**Comment by paul-hammant** [comment]
Take a look at the other two bug reports for 'testability' - https://github.com/paul-hammant/ngWebDriver/issues?utf8=%E2%9C%93&q=is%3Aissue%20testability

**Comment by venkat6080** [comment]
Thank you it working,
1. How to handle the same situation in different Pages. we need to create different objects right or is there any other solution ?(Example:: Login Page and Home Page)
2. I didn't get these URL meaning why posted (https://www.w3schools.com/cssref/css_selectors.asp).
Could you please elaborate the usage of css selectors.

**Comment by paul-hammant** [comment]
For both (1) and (2), I do not understand what you are asking.

**Comment by venkat6080** [comment]
1. How to handle the same situation in different Pages. we need to create different objects right or is there any other solution ?(Example:: Login Page (login.html) and Home Page (home.html))

Example: In Login Page here i am creating here changing Root Selector name as login.html
NgWebDriver login_ngdriver = new NgWebDriver((JavascriptExecutor)driver).withRootSelector("[app-run=\"login.html\"]");
 ByAngular.Factory byAngular = login_ngdriver .makeByAngularFactory();

In HomePage here i am creating here changing Root Selector name as home.html

NgWebDriver home_ngdriver = new NgWebDriver((JavascriptExecutor)driver).withRootSelector("[app-run=\"home.html\"]");
 ByAngular.Factory byAngular = home_ngdriver .makeByAngularFactory();



2. In these post (Take a look at the other two bug reports for 'testability' - https://github.com/paul-hammant/ngWebDriver/issues?utf8=%E2%9C%93&q=is%3Aissue%20testability)
when i look at these issues you psot the css selectors link. what is the use of the css selectors in these post

**Comment by manoj9788** [comment]
@venkat6080 You need a rootSelector to pass into NgWebDriver, basically you are helping NgWebDriver find Angular apps on a page. It's usually ng-app in a proper Angular page, sometimes it could also be a part of a page and on those occasions, It could be a CSS selector is what @paul-hammant meant there. Refer [here](https://github.com/paul-hammant/ngWebDriver#alternate-selectors)
On your Application under test find a root element and pass in there.

**Comment by venkat6080** [comment]
@manoj9788 
Thank You !!

**Comment by manoj9788** [comment]
@venkat6080 As I said, the page that you are using is not a proper Angular page where ng-app is not defined, in that case, you will have to come up with a rootSelector. [fooBar] is not a Selector, it's just an example instead of 'fooBar' it could be anything as in your application under test like [xxxxx] instead of xxx and fooBar it should be an attribute of any element on the given page, where angular is defined. Hope that helps.  Read more here about [rootElement](https://github.com/angular/protractor/blob/4b7cada1317079c20ddf1bb105303e21adba6e32/lib/config.ts#L377)

**Comment by paul-hammant** [comment]
Readers: Specifying rootSelector probably solved it for the OP
