### ISSUE TITLE
package com.paulhammant.ngwebdriver does not exist 

### ISSUE THREAD

**Issue by venkat6080** [paul-hammant/ngWebDriver#51]
Hi, I am using Maven getting the compile error for ngWebDriver.

Here i am using these versions : 

Selenium-WebDriver (3.4)
Java (1.8.0.31)
Ng-Webdriver (1.1)

Error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
3:compile (default-compile) on project Pratice-Template: Compilation failure: Compi
lation failure:
[ERROR] /D:/Git_Merge/src/main/java/utils/Utils.java:[93,35] package com.paulham
mant.ngwebdriver does not exist

**Comment by paul-hammant** [comment]
Make a new github repo that shows that problem, please. I need to be able to fully reproduce it from a repo that I can clone, cd into, and do `mvn install`

**Comment by venkat6080** [comment]
Hi paul-hammant,
Problem is solved.

Root Cause for Error is :
In Maven i using main folder in place of test folder for classes creation.
When i comment on the scope it's working fine. 
		<dependency>
  			<groupId>com.paulhammant</groupId>
  			<artifactId>ngwebdriver</artifactId>
  			<version>1.0</version>
 			
		</dependency>

**Comment by paul-hammant** [comment]
Good news :)
