### ISSUE TITLE
WaitForAngular2ToFinish() is failing with an error "Could not find testability for element. "

### ISSUE THREAD

**Issue by Nandesh7** [paul-hammant/ngWebDriver#53]
@paul-hammant 

First of all,Thank you for such an amazing work on ngWebDriver. I am trying to implement it for one of the sites built on Angular 4. I've gone through the sample test & tried all feasible steps - No luck. May be I am missing something. 

I am using ngWebDriver in conjunction with QAF & here is how my code looks

       `QAFExtendedWebDriver driver = getDriver();
	NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor)driver);`

when the below line executes, I am seeing an exception 
`ngWebDriver.WaitForAngular2ToFinish();`

TestNG: e to bad ' +\n          'obfuscation.');\n    } else {\n      throw new Error('Cannot get testability API for unknown angular ' +\n          'version \"' + window.angular.version + '\"');\n    }\n  } catch (err) {\n    callback(err.message);\n  }\n"} 
TestNG: );
    } else {
      throw new Error('Cannot get testability API for unknown angular ' +
          'version "' + window.angular.version + '"');
    }
  } catch (err) {
    callback(err.message);
  }
}] Result: Could not find testability for element. 

The app root on DOM shows something like this
`<app-root _nghost-c0="" ng-version="5.0.3">`

**Comment by paul-hammant** [comment]
Use github-pages to make a tiny static site reproducing the problem please. I will help you if you do that and show me a whole **minimal** test class (with maven pom etc) that illustrates the problem.

**Comment by paul-hammant** [comment]
@Nandesh7 how's that reproduction going?

**Comment by shobhitgupta** [comment]
Hi Paul,

I am facing the same issue for one of the internal application. Can you guide me for the specific questions I should ask the developers or anything to look out within the application

**Comment by paul-hammant** [comment]
@shobhitgupta **separate issue please**, make it reproducibe, be sure to have read https://github.com/paul-hammant/ngWebDriver#helping-ngwebdriver-find-angular-apps-in-a-page very carefully first.

**Comment by paul-hammant** [comment]
closing as OP non responsive.
