### ISSUE TITLE
waitForAngularRequestToFInish() does help and webdriver is ahead of angular request.

### ISSUE THREAD

**Issue by amitpokhrel** [paul-hammant/ngWebDriver#55]
I am trying to write a simple test in webdriver for angular site. Beow is my code:
`@Test
    public void testapp() {

        System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");

        ChromeDriver driver = new ChromeDriver();
        driver.get("http://nvscmlind2:8080/indv301");
        new NgWebDriver(driver).waitForAngularRequestsToFinish();

        WebElements webElements = new WebElements(driver);
        webElements.filterIcon.click();
        new NgWebDriver(driver).waitForAngularRequestsToFinish();

        SeleniumUtils.selectByVisibleText(webElements.columnSelect, "Age");
        SeleniumUtils.selectByValue(webElements.filterSelect, ">");
        SeleniumUtils.sendKeysToInput("10", webElements.filterValue);
        webElements.applyButton.click();

    }`
`private static class WebElements {
        public WebElements(WebDriver driver) {
            PageFactory.initElements(driver, this);
        }

        @FindBy(xpath = "//app-data-grid")
        private WebElement dataGrid;

        @FindBy(xpath = "//app-customization//i[@class='ic-gear']")
        private WebElement gearIcon;

        @FindBy(className = "close-modal")
        private WebElement closeModal;

        @FindBy(className = "ic-filter")
        private WebElement filterIcon;

        @FindBy(xpath = "//app-modal-content//select[@formcontrolname='name']")
        private WebElement columnSelect;

        @FindBy(xpath = "//app-modal-content//select[@formcontrolname='op']")
        private WebElement filterSelect;

        @FindBy(xpath = "//app-modal-content//input")
        WebElement filterValue;

        @FindBy(xpath = "//app-modal-content//button[text()='Apply']")
        WebElement applyButton;
    }`
when I execute the code I get below error:
`org.openqa.selenium.NoSuchElementException: Cannot locate element with text: Age`

Now when I implement the same test in protractor it works fine everytime.
`describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://nvscmlind2:8080/indv301');
	element(by.css('.ic-filter')).click();
	element(by.xpath('//app-modal-content//select[@formcontrolname="name"]')).element(by.cssContainingText('option', 'Age')).click();
	element(by.xpath('//app-modal-content//select[@formcontrolname="op"]')).element(by.cssContainingText('option', 'Greater than')).click();
	element(by.xpath('//app-modal-content//input')).sendKeys('10');
	element(by.xpath('//app-modal-content//button[text()="Apply"]')).click();
	//browser.driver.sleep(20000);
  });
});`

Why does it not work?

**Comment by paul-hammant** [comment]
I processed a pull request over the w/e - maybe I need to publish the jar ... because the client-side JS (which is copied from Protractor) was updated.

**Comment by amitpokhrel** [comment]
does this mean we should expect new version of the library? If so, do  you have a tentative deadline?

Thanks.

**Comment by paul-hammant** [comment]
ngWebDriver doesn't have to release every time Protractor releases, no. Not even every time the JS client JS script changes. For example, if the upstream team makes a release with only comment changes in the JS script.

1.1.1 of ngWebDriver released

**Comment by amitpokhrel** [comment]
Thank you for the update. 
Let me be clear with my concern. If I use ngWebDriver in my project(lets say version 1.1.1), now if there is some change in Angular/Protractor and new version of Angular/protractor releases(with code changes and not just comments), will this have an impact on my project? Will my tests break because of this?

**Comment by paul-hammant** [comment]
> will my ngWebDriver tests break every time Protractor releases?  (paraphrase)

Not every time, no.
