### ISSUE TITLE
Need clarity on waitForAngularRequestsToFinish()

### ISSUE THREAD

**Issue by dantran** [paul-hammant/ngWebDriver#57]
Is waitForAngularRequestsToFinish() a one time deal? it is not clear to me how often we need to call it. in my web test, I force this at every page object load which I don't feel right.

I also posted same question at https://groups.google.com/forum/#!topic/selenium-users/JsIkx-KLujI, not able to get traction

**Comment by symonk** [comment]
You call it whenever you need, best server in some sort of reusable functions, maybe a click method might wait before performing the click or after etc, it is not a set once and automatically applies where necessary

**Comment by symonk** [comment]
*served. Sorry for typos I’m on my phone 😊

**Comment by dantran** [comment]
is there a way to figure out if a click requires calling this wait?

**Comment by symonk** [comment]
Never tried but implementing WebDriverEventListener and doing some stuff there could be useful, never tried myself tho

**Comment by paul-hammant** [comment]
My experience tells me that it is down to the page and app. There are times when you want to fail a test if Angular didn't do its thing in the page within so many seconds. Sure that feels like a non-functional assertion, when WebDriver is more often used for functional assertions, but is a legitimate use case. Because of that, I'm against every call to WebDriver having a waitForAngularRequestsToFinish() call. It is my recommendation that the user uses it once on the initial page load (or not as above), then does effective waitFor()s after that: within() and without().

**Comment by pavannarrasdet** [comment]
Hi Paul,
I tried to perform an end to end scenario with ng webdriver. after login, its not able to validate tile of home page and then its not able to identify elements and giving below error:

code:
package sample.example;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;

import com.paulhammant.ngwebdriver.ByAngular;
import com.paulhammant.ngwebdriver.ByAngularBinding;
import com.paulhammant.ngwebdriver.NgWebDriver;

public class NGTEST
{
	static NgWebDriver ngdriver;
	static WebDriver driver;
	
	public static void main(String[] args)
	{
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
		System.setProperty("webdriver.ie.driver","C:\\Users\\pnarra\\Documents\\MyJabberFiles\\jsyed101@corpimsvcs.com\\phyconUI\\phyconUI\\Drivers\\IEDriverServer_Win32_2.47.0\\IEDriverServer.exe");
		driver = new InternetExplorerDriver(capabilities);	
		//driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.manage().timeouts().setScriptTimeout(60, TimeUnit.SECONDS);
		ngdriver= new NgWebDriver((JavascriptExecutor)driver);
		driver.get("http://pdm-dev4.linkhealth.com");		
		ngdriver.waitForAngularRequestsToFinish();	
		if(driver.getTitle().toString().equals("Sign In With Your Optum ID - Optum ID"))
		{
			System.out.println("Entered");
			List<WebElement> models = driver.findElements(ByAngular.model("model"));
			models.get(0).click();
			models.get(0).sendKeys("MArthamCorp4");
			models.get(1).click();
			models.get(1).clear();
			models.get(1).sendKeys("Testcorp44");
			driver.findElement(By.id("SignIn")).click();
			if(driver.getTitle().toString().equals("My Practice Profile"))
			{
				System.out.println("Application found");
			}
			else
			{
				System.err.println("Application not found");
			}
			WebElement listObj = driver.findElement(By.id("taxId"));
			Select list = new Select(listObj);
			list.selectByIndex(0);
			WebElement tinObj = driver.findElement(ByAngular.model("vm.selectedProviderObj.tinObj"));
			Select tin = new Select(tinObj);
			System.out.println("The default populated tin was: "+tin.getFirstSelectedOption().getText());
		}
		
	}
}



error:
Listening on port 39584
Only local connections are allowed
Entered
Application not found
Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to find element with id == taxId (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 359 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'LH7U05CG63526LQ', ip: '10.195.91.92', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, proxy={proxyType=}, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:39584/, javascriptEnabled=true, ignoreProtectedModeSettings=true, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 3ffb3a01-d98a-4237-ad4f-dd315f3cd286
*** Element info: {Using=id, value=taxId}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at sample.example.NGTEST.main(NGTEST.java:52)
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."


Do I need to use selenium explcit wait like wait,until() thing? or fluent wait? I tried to add waitforAngularRequestotfinish after sign in button as well

DOM:
<select name="taxId" class="full-width standard-select ng-pristine ng-untouched ng-valid ng-empty" id="taxId" ng-model="vm.selectedProviderObj" ng-disabled="!vm.selectedResponsibleOrg.uhcId" ng-change="vm.getTINsByMPIN()" ng-options="corporateProfile.providerName for corporateProfile in vm.corporateProfiles | orderBy:'providerName'"><option selected="selected" value="">Select a value</option><option value="object:26" label="ARIZONA COMMUNITY PHYSICIANS">ARIZONA COMMUNITY PHYSICIANS</option><option value="object:27" label="BANNER HEALTH ARIZONA">BANNER HEALTH ARIZONA</option><option value="object:28" label="EAGLE PHYSICIANS &amp; ASSOCS">EAGLE PHYSICIANS &amp; ASSOCS</option><option value="object:29" label="KALKANIS PETER">KALKANIS PETER</option><option value="object:30" label="NYU HOSPITALS CENTER">NYU HOSPITALS CENTER</option></select>


could you advise whether to go with explicit or not, however I will try to add different sync statemnts by the time I get response from you.

Thanks,
Pavan
