### ISSUE TITLE
Cannot read property '$$testability' of undefined

### ISSUE THREAD

**Issue by shobhitgupta** [paul-hammant/ngWebDriver#59]
The bootstrapping of angular is done manually so there is no [ng-app] tag available in DOM . App tag is used in the application . I am attaching a html snippet for the same. As its an internal application , so I can't replicate it externally. I am getting the "testability" error 
![app](https://user-images.githubusercontent.com/7817996/37290447-289f1a0a-2604-11e8-8b6c-840ce55120b9.PNG)

Let me know if you need additional details

**Comment by shobhitgupta** [comment]
Tried the following code but this also didn't work for me 
ByAngular.Factory baf = ByAngular.withRootSelector("[app]");
ByAngularModel foo = baf.model("test");

**Comment by shobhitgupta** [comment]
Any update ?

**Comment by paul-hammant** [comment]
Can you make a "Hello world" example in a HTML page that actually runs? I'll take a look if you do that, otherwise I'm inclined to say "unsupported".

You see that you have an unconventional `<app>` element. In Xpath you could find that with `//app`. With css selectors that just `app`.  You might nor need anything as complicated as `[app~='full-height']`. Also the square brackets are for attributes and you have an element - refer https://www.w3schools.com/cssref/css_selectors.asp.

You yourself are in QA automation or Dev, @shobhitgupta ?

**Comment by shobhitgupta** [comment]
I am in QA Automation ... but if you need any specific information from Development team , I can get that. Earlier a team used protractor for this application .

**Comment by paul-hammant** [comment]
Is it possible your devs will help you make a reproduction of this that can be uploaded to GitHub that doesn't leak any company secrets?

**Comment by shobhitgupta** [comment]
I am exploring that option and will let you know once we have that working model with us

**Comment by paul-hammant** [comment]
Cool - looking forward to it :)

**Comment by shobhitgupta** [comment]
Still trying to get the similar app uploaded on Github. What I understand with the developers is that the manually bootstrapping AngularJS , so there won't be any ng-aa

**Comment by paul-hammant** [comment]
As long as it is reproducible for me, I can work with it :)

**Comment by shobhitgupta** [comment]
https://utsavagrawal23.github.io/
The above sample application uses the similar architecture. Can you please have a look at it

**Comment by shobhitgupta** [comment]
DriverFactory.initiateDriver("Chrome");
        NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor) DriverFactory.getDriver());
        DriverFactory.getDriver().get("https://utsavagrawal23.github.io/");
        DriverFactory.getDriver().findElement(ByAngular.model("test")).sendKeys("hello");

Trying to enter some value in the edit field having ng-model value as "test"

**Comment by paul-hammant** [comment]
Could you add that to the repo please as a class so that all I have to do is clone and run "mvn test"

**Comment by shobhitgupta** [comment]
It worked for me by having DriverFactory.getDriver()).withRootSelector("app") . But still getting error for the method  ngWebDriver.waitForAngular2RequestsToFinish();

Below is the error 

Exception in thread "main" org.openqa.selenium.ScriptTimeoutException: asynchronous script timeout: result was not received in 30 seconds
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MGIT14452550W', ip: '10.32.35.56', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.35.528161 (5b82f2d2aae0ca..., userDataDir: C:\Users\guptasho\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true}
Session ID: e0784f8d99c6f133672d5a7c5a9953b1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:555)
	at com.paulhammant.ngwebdriver.NgWebDriver.waitForAngular2RequestsToFinish(NgWebDriver.java:75)
	at dummy.TestingClass.main(TestingClass.java:28)

**Comment by paul-hammant** [comment]
`ngWebDriver.waitForAngular2RequestsToFinish()` is a different but. The method will be deleted soon. Just use `ngWebDriver.waitForAngularRequestsToFinish()`

**Comment by paul-hammant** [comment]
Is there anything in the README.md file that could be improved to help future people looking for $$testability undefined help?

**Comment by shobhitgupta** [comment]
I  think having a example to demonstrate how to perform the click or sendkeys operation using webdriver might help others to understand it in a better way

**Comment by paul-hammant** [comment]
That example pertains to $$testability or just more generally ?

**Comment by rahilliard1** [comment]
Both.

**Comment by shobhitgupta** [comment]
NgWebDriver ngwd = new NgWebDriver(webDriver).withRootSelector("something-custom");
ByAngular.Factory factory = ngwd.makeByAngularFactory()
WebElement element = webDriver.findElement(factory.exactRepeater("day in days"));

Something like this would give more clarity to someone who is not having in depth knowledge of NGWebdriver .

Also I have a question regarding repeater. In the examples you shared , will that work only if there is <tr> and <td> available within the repeater section ?

In my application, we have <div> sections with no unique identifier , so how can I specify the coloumn to fetch a particular value ?

**Comment by paul-hammant** [comment]
Are these clearer?  

1. https://github.com/paul-hammant/ngWebDriver/blob/master/README.md#repeater

2. https://github.com/paul-hammant/ngWebDriver/blob/master/README.md#helping-ngwebdriver-find-angular-apps-in-a-page

**Comment by paul-hammant** [comment]
README updated to be clearer

**Comment by shobhitgupta** [comment]
Thanks for updating README , looks better but still needs more clarity is what is "foo.name" . Is it another NG-Repeater or an ID within the section ?

**Comment by paul-hammant** [comment]
@shobhitgupta Please limit discussions in issue #59 to be $$testability related. If you want to change the subject, raise a new ticket.
