### ISSUE TITLE
How to implement this with the page factory and pom model

### ISSUE THREAD

**Issue by babushiekdawood** [paul-hammant/ngWebDriver#61]
Can you give me some heads up or some samples like u have for others

**Comment by paul-hammant** [comment]
I do not know what you are asking.

Does this https://github.com/paul-hammant/ngWebDriver/blob/117f23b40fd945dbdd4c16921fdae3d855bc1194/src/test/java/com/paulhammant/ngwebdriver/FindByNgWebDriverTest.java not help you understand PageFactory?

**Comment by babushiekdawood** [comment]
Got it after doing some deep diving. Thanks closing this issue,

**Comment by paul-hammant** [comment]
Hey @babushiekdawood, take a look at the README for ngWebDriver and suggest some improved text so that the next person has a better chance of quickly getting what they are looking for :)

**Comment by babushiekdawood** [comment]
Yup, Sure Paul. Thanks for your help. ngWebDriver is great, i am just started to work with ngWebDriver will come back if there any assistance required.

**Comment by paul-hammant** [comment]
No, I'm asking you to contribute some text, dude :)

**Comment by babushiekdawood** [comment]
oh sure Paul 👍
