### ISSUE TITLE
ngdriver.waitForAngularRequestsToFinish();

### ISSUE THREAD

**Issue by pavannarrasdet** [paul-hammant/ngWebDriver#62]
@paul-hammant  , Hi Paul
I am a new user of your tool :)
Hope this gives me great exposure towards my angular application automation in Java.
I got some doubts here:
ngdriver.waitForAngularRequestsToFinish(); , what does this statement do? and
2) if I would like to run my test in sauce labs .. do you have any separate capabilities for this library or its same as Selenium webdriver ?

please advise

**Comment by paul-hammant** [comment]
waitForAngularRequestsToFinish() is documented here - https://github.com/paul-hammant/ngWebDriver#waiting-for-angular-to-finish-async-activity.

If you are not sure you need it, try making a test without it.

I answered #2 in email and will not answer it again in an issue tracker.

Please use this forum to raise bugs, not seek help. Perhaps there is a developer in your team who can help you get setup.

**Comment by pavannarrasdet** [comment]
Thanks @paul .. I can try myself and comeback to you if I get any bug ..
I will explore on your tool :)
