### ISSUE TITLE
Specified root selector but still getting error Cannot read property '$$testability' of undefined

### ISSUE THREAD

**Issue by dimplechhabadia** [paul-hammant/ngWebDriver#64]
Test app url : https://angularjs.org/.  specified the root selector but still getting 
ERROR!
org.openqa.selenium.WebDriverException: 
unknown error: Cannot read property '$$testability' of undefined
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'HOU-QA-1', ip: '192.168.1.10', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.38.552522 (437e6fbedfa876..., userDataDir: C:\Users\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 21e9f50b6f254e92b4de001cda20bd24
	at com.testing.AppTest.testGoogle(AppTest.java:33)

      System.setProperty("webdriver.chrome.driver", "path of chromedriver.exe");
    	ChromeDriver driver = new ChromeDriver();
    	driver.get("https://angularjs.org");
       	NgWebDriver ngWebDriver = new NgWebDriver(driver).withRootSelector("todoApp");
       	ByAngular.Factory baf = ngWebDriver.makeByAngularFactory();
        WebElement element = driver.findElement(baf.model("todoList.todoText"));
    	element.sendKeys("Hello");

**Comment by paul-hammant** [comment]
What is the code in JavaScript for Protractor that works for https://angularjs.org/?

**Comment by paul-hammant** [comment]
Never mind ... you have your selector wrong, it should have been '[module=todoApp]' not 'todoApp'. There's a section in the readme all about that.
