### ISSUE TITLE
Issue on Set script timeout

### ISSUE THREAD

**Issue by pavannarrasdet** [paul-hammant/ngWebDriver#66]
Hi Paul,

Good Morning! hoping that you are doing great !

it was noticed that, when i mentioned setScriptTimeOut statement in tests, during first page loading , it was waiting blindly for sometime even after page load completes and element is ready to perform actions.

Can i turn off setScripttimeout statement since it needs only to ececuteAsyncScripts. or is it mandate to define this in order to use ngWebdriverLocators since these locators calls JSExecutor in backend per my understanding of your framework design ?

i am actually using webDriverwaits and i am good with that, is there any conflict of usage among these two (both scripttimeout and webdriverwait)?

Kindly , please give me your insight onthis.

thanks,
Pavan

**Comment by paul-hammant** [comment]
Hi Pavan.

Any chance of an example on GitHub that I can run and attach a debugger to to see the problem?  I.e. the smallest possible reproduction of the problem?

- Paul
