### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by lilletech** [paul-hammant/ngWebDriver#67]
Is it compatible with angular 4. I'm always having a timeout exception while instantiating ngwebdriver

**Comment by symonk** [comment]
Hi @lilletech can you please provide us with a Minimal, Complete, and Verifiable example, makes it easier to help and diagnose potential issues. 

Thanks again

**Comment by naga2192** [comment]
Hello ,

Can you please confirm ,is it compatible with angular 6 application ?

**Comment by paul-hammant** [comment]
Should be. Let me know if it is not.
