### ISSUE TITLE
POM @FindBy List elements throws Null Pointer Exception

### ISSUE THREAD

**Issue by kapomaho** [paul-hammant/ngWebDriver#70]
Hello,

Once declaring the element like at below;

	@com.paulhammant.ngwebdriver.ByAngularModel.FindBy(model="customer.title")
	public List<WebElement> name;

for(int i=0;i<name.size();i++)
		{
			if(name.get(i).isDisplayed())
			{
				write(name.get(i), "asda");
				break;
			}
		}
it throws Null Pointer. However when calling the without using POM it works.

              List<WebElement> name=	driver.findElements(ByAngular.model("customer.title"));
	
	name.get(1).sendKeys("sada");

Also WebElement without list also works nice ;
	@com.paulhammant.ngwebdriver.ByAngularModel.FindBy(model="customer.title")
	public WebElement name;
	
name.sendKeys("asda");

**Comment by paul-hammant** [comment]
Which site?  Can you show the the code that instantiates WebDriver and ngWebDriver? Can you successfully locate any other Angular elements?

**Comment by kapomaho** [comment]
This is my base class.

public class Base {
    public ChromeDriver driver;
    public WebDriverWait wait;
    public String url;
    public Actions action;	
	private DesiredCapabilities capability = null;
	public Properties prop;
	public NgWebDriver ngWebDriver;
	
    public WebDriver getDriver() {
        return driver;
    }

    public void setup () throws FileNotFoundException, IOException {
		System.setProperty("webdriver.chrome.driver", "/usr/local/bin/chromedriver");

        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        ngWebDriver = new NgWebDriver(driver);
        driver.manage().window().maximize();
             
        
        if(System.getenv("url")!=null && !System.getenv("url").isEmpty())
        {
        	url=System.getenv("url");
        }
        else
        {
        	url=getConf("url");
        }
        
        driver.get("https://demo.thingsboard.io/login");
        wait = new WebDriverWait(driver,20);

    }
This is my PageObject file.

	@com.paulhammant.ngwebdriver.ByAngularModel.FindBy(model="customer.title")
	public List<WebElement> name;

	public void addCustomer() throws InterruptedException
	
	{

		click(addCustomerIcon);
		//waitAngular();
		
		for(int i=0;i<name.size();i++) //This point i got Null Pointer
		{
			if(name.get(i).isDisplayed())
			{
				write(name.get(i), "asda");
				break;
			}
		}
	}

This is the test case
@Test 
    public void login () throws Exception {
    	
    	
    	setup();
    	LoginPage login=PageFactory.initElements(driver, LoginPage.class);	
    	login.doLogin().navigateCustomers().addCustomer();
}

**Comment by paul-hammant** [comment]
Can you tell me the lines of code in `doLogin()` please.

**Comment by kapomaho** [comment]
Hello,

@FindBy(id="password-input")
public WebElement password;  
 
 
@FindBy(xpath="//span[text()='Login']")
public WebElement loginButton;  
 
 
@com.paulhammant.ngwebdriver.ByAngularModel.FindBy(model="vm.user.name")
public WebElement userNameang  ;  //vm.user.name

@FindBy(css="md-icon[aria-label='home']")
public WebElement homePage;  
  
  public LoginPage(WebDriver driver){    
    this.driver=driver;
    wait =new WebDriverWait(driver,30);
  }
  public void waitAngular()
  {
    
    new WebDriverWait(driver, 50).until(new ClientSynchedWithServer());
 
  }
  
  public HomePage doLogin() throws Exception{
     //new WebDriverWait(driver, 10).until(new ClientSynchedWithServer());
    //xpathParcasiMesajKontrolEt(kullaniciAdiLabel, "Kullanıcı Adı");
    
    waitAngular();
    
    write(userNameang,getConf("username"));
    //waiting(1000);
    write(this.password,getConf("password"));
  //  waiting(1000);
    //jsClick(loginButton,driver);  
    click(loginButton);
    //Thread.sleep(5000);
    //driver.navigate().refresh();
    waitAngular();
 
    verifyText(homePage, "home");
    return PageFactory.initElements(driver, HomePage.class);
 
  }  

if this is not enough i can share with you my project through github.

**Comment by paul-hammant** [comment]
You saw all the @FindBy inner-classes built into ngWebDriver itself - right?

![image](https://user-images.githubusercontent.com/82182/43909587-996c3aa6-9bf2-11e8-9969-edd60c5bb2a0.png)

**Comment by paul-hammant** [comment]
I made ehancements to Selenium itself to facilitate these new FindyBys

**Comment by kapomaho** [comment]
Hello,

Yes . Before discovered your useful library i had been using css locators. At this point only problem is declaring list element.  When making debugging the other elements are initialized but list element could not initiliaze and null.

**Comment by kapomaho** [comment]
What should we make to using your enhancements ?

**Comment by paul-hammant** [comment]
What do you mean "what should we make" ?

**Comment by kapomaho** [comment]
Hello,
Sorry my english is not good . i supposed you made new enhancement about my problem(List elements) and asking how we can pull that new version to use this. 

Actually the main problem is when try to add a new Customer on https://demo.thingsboard.io/ there are 2 same angular form elements on the html. First one is hidden and the second is the actual form elements. Because of this reason i need to locate the elements as a List. 

![image](https://user-images.githubusercontent.com/3909094/43911875-425ee4f4-9c09-11e8-89cf-54216c866c52.png)

**Comment by paul-hammant** [comment]
The ngWebDriver specific FindBy's were added some time ago. They were not detailed in the README. They are now. Have a look at the README. Search for FindBy. Copy lines of code in to your solution.  Most likely, use `@ByAngularModel.FindBy("customer.title")`.

**Comment by kapomaho** [comment]
i am so sorry about taking your time but i cant use @ByAngularModel.FindBy annotation.  i have tried 1.1.3 and 1.1.4 version .i have tried 	@ByAngularModel.FindBy(model = "customer.title") and also this made null pointer.
	
![image](https://user-images.githubusercontent.com/3909094/43913174-fd97a3ac-9c0c-11e8-8769-9613fde07b0b.png)

**Comment by paul-hammant** [comment]
README updated with more info on how to use FindBy

**Comment by kapomaho** [comment]
Now i looked . and declaring the variable same as your suggestion.it gives error .

![image](https://user-images.githubusercontent.com/3909094/43913771-a630c2f4-9c0e-11e8-965d-d0a8cccf2312.png)

**Comment by kapomaho** [comment]
There is the repo;

https://github.com/kapomaho/Thingsboard

**Comment by paul-hammant** [comment]
`@ByAngularModel.FindBy(model= "customer.title")` should be it.

**Comment by kapomaho** [comment]
Hello Mr.Paul,

Your FindBy's on Page Object Model are working smoothly for singular Angular WebElement . However when try to declare as a List<WebElement> it gets NullPointerException.  

For an instance ; 

@ByAngularModel.FindBy(model= "customer.title")
public WebElement name;

it works as a expected . 

@ByAngularModel.FindBy(model= "customer.title")
public List<WebElement> name;

This throws exception. When perform a debugging it is easily seen object could not initialized.

Thanks for interest.

**Comment by paul-hammant** [comment]
I am able to log in.

Where on this page is customer.title ?

![image](https://user-images.githubusercontent.com/82182/43971538-5ca5ed24-9cc9-11e8-928b-bea9cfda35bd.png)

**Comment by kapomaho** [comment]
Hello,
Clicking on "Customers" link of the left panel and later click "+" icon it will open Add Customer screen

**Comment by paul-hammant** [comment]
Which Angulat attribute are we aiming to locate:

![image](https://user-images.githubusercontent.com/82182/43988704-38f722c0-9d33-11e8-9d4a-81e5b7e9e423.png)

**Comment by kapomaho** [comment]
Hello Mr.Paul,

Without using Page Object Model it works properly. Also other than the code you share this command also works;
	driver.findElements(ByAngular.model("customer.title")).get(1).sendKeys("hello");

However in case of the declare Page Object  it throws null pointer.
@ByAngularModel.FindBy(model= "customer.title")
public List<WebElement> name;

With any singular Angular element with Page Object your FindBy's are working nice. However trying to declare as a List element. it does not work.

Does your library not compatible for List Element on Page Object Model.? Could we only use your library on singular Angular element ?

Thanks.

**Comment by paul-hammant** [comment]
I didn't do any special coding for Lists. Does @FindBy(className="") work with lists?

**Comment by kapomaho** [comment]
Yes. Each "By" attributes (xpath,css,classname,id,name)works properly with lists. Do you have any planning to enhancements about Lists on Page Object Model?. Because you may also noticed that there are 2 same locator on the page for ThingBoards . Because of the first locator is hidden we need to select second one. Naturally we have to declare a variable as List. In this case, it looks like we won't be able to use the Page Object Model structure if we use your library.

Not to mention only “Thingsboard.” Getting Null pointer error when defining List WebElement using POM for any web application.

**Comment by kapomaho** [comment]
Hello Mr.Paul,

i have also tried to use @FindBys annotation (When the required WebElement objects need to match all of the given criteria use ) . But your's custom AngularBy annotation is not compatible for it too.

![image](https://user-images.githubusercontent.com/3909094/43996137-07edb3f0-9dc5-11e8-8920-d3a05bb16bbf.png)

**Comment by paul-hammant** [comment]
`@FindBys` ... that's a java limitation :-(

![image](https://user-images.githubusercontent.com/82182/43999109-70ce4d0c-9dfd-11e8-9525-4472ee9cc89c.png)

**Comment by paul-hammant** [comment]
Yup - I've found some lines of code in Selenium itself that is the blocker, I think.  DefaultFieldDecorator lines 88-90.

**Comment by kapomaho** [comment]
Hello Mr. Paul,
I look forward to hearing from you good news  :) . 
Thanks.

**Comment by paul-hammant** [comment]
I talked to Simon Stewart and he said that there's upper limits in the @Findby logic.

**Comment by paul-hammant** [comment]
Changing to wont-fix, and people needing this should do the locator without @FindBy logic
