### ISSUE TITLE
Testing hybrid Angular 1+2 app

### ISSUE THREAD

**Issue by andrewg78** [paul-hammant/ngWebDriver#72]
I'm having issue to test a hybrid app
I do not have root element in my ng1 app so I do not know how to use RootSelector.
![image](https://user-images.githubusercontent.com/2042344/44577369-35d44380-a791-11e8-9c22-e8b2800edc5e.png)

Here is the link to the same issue with some samples on plunker
https://github.com/angular/protractor/issues/2944
https://github.com/angular/protractor/issues/3238

**Comment by paul-hammant** [comment]
Yeah, add a contrived root attribute like `<div my-ng-root .... />`

**Comment by paul-hammant** [comment]
Andrew?

**Comment by andrewg78** [comment]
Hi Paul.
I think I found root cause of my issue, but have no clue how to resolve it.
There is an older version of the app under test which works fine with the waitForAngularRequestsToFinish method.
I do not have to set root selector and it works just fine.
The newer version has NO ng-app attribute, so I guess this is the reason why this wait method doesn't work.
If Im right, is there any way to inject it there  during the test or any other workaround ?

**Comment by paul-hammant** [comment]
Can the dev team help you with here?  Cooperating for sake of testability by adding a more convention ng-app root ?
