### ISSUE TITLE
Use of NgWebDriver

### ISSUE THREAD

**Issue by prashantjeetsingh** [paul-hammant/ngWebDriver#73]
Hi Paul,
I am new to protractor testing.
Can you help me in understanding, if we are passing the webDriver instance to NgWebDriver constructor then why we are not using ngWebDriver instance for finding the elements? why we are using webDriver

All have read your github documentation but still in doubt.

Please help me in understanding it

**Comment by prashantjeetsingh** [comment]
Thanks, Paul for the info

**Comment by paul-hammant** [comment]
You're welcome.
