### ISSUE TITLE
Angular version support with ngWebDriver

### ISSUE THREAD

**Issue by sreenivaskilari** [paul-hammant/ngWebDriver#75]
Hi,
As I am working on developing a framework(selenium + ngWebdriver) which will be used for a various projects. I need the info about ngWebdriver support with angular versions.

**Comment by paul-hammant** [comment]
ngWebDriver works with all versions of AngularJs after v1.0 and all Angular versions. Is that what you wanted?

**Comment by sreenivaskilari** [comment]
Thanks, Paul for the quick response, Yes this is was what I am looking for. We are planning to add ngWebdriver to our selenium framework to bring in angular support. I think it will support until angular 6. But new release of angular i.e., 7 I heard there are many changes the way developers develop, so I was wondering if it affects existing DOM structure and element identification mechanism which ngWebdriver currently has?

**Comment by paul-hammant** [comment]
Relax: the code you work on with ngWebDriver+Selenium (also look at FluentSelenium) is a lot more stable than the dev's code in JavaScript/TypeScript under NPM in order to build/deploy an Angular app.

If you're thinking about not starting an Angular app because of fears of not having a smooth upgrade path later, then yeesh, that's a damning indictment of our industry :-(

**Comment by skullz03** [comment]
How does one grab elements other than by "css" Angular 2+ has the ability of making a custom locators. If I don't want to use "css" - what are my options? The By.modal, by.binding used to work with Angular js and Angular 2 onwards i doubt anyone uses these. What would be your suggestion in such cases?

**Comment by paul-hammant** [comment]
Leave #75 closed, start a new issue, show the actual code you'd wish to be able to do. Preferably in conjunction with an online demo of the HTML rectangle you'd like to locate
