### ISSUE TITLE
NgWebdriver working only after reloading the page

### ISSUE THREAD

**Issue by sarojpurbey324** [paul-hammant/ngWebDriver#77]
Hi Paul,

I have to reload the page every time for ngWebDriver to work. If I don't reload, it takes a very long time to execute tests. After reloading, the tests run smoothly. What could I do to avoid reloading the page every time?

**Comment by paul-hammant** [comment]
How can I reproduce your problem?

**Comment by sarojpurbey324** [comment]
I cant give my organisation Website link  due to  security issue. And I don't know how to reproduce that problem. If I had known the issue or problem I would have solved it.

**Comment by paul-hammant** [comment]
I can't help unless you can reproduce. See if you can make a cut-down version of the problem, for me to see, that doesn't have any intellectual property

**Comment by sarojpurbey324** [comment]
Thank you Paul for being concerned to my issue. But i really don't know how to reproduce that issue. Our website is completely build on Angular.
