### ISSUE TITLE
NgWebDriver not working for Long lived HTTP connection

### ISSUE THREAD

**Issue by sarojpurbey324** [paul-hammant/ngWebDriver#78]
We have an angular application that receives push notification from server using SSE (Server sent events). At angular we have eventSource implemented to listen to the server. As this connection between angular and server never ends, waitForAngularRequestToFinish() waits for all the request to complete which never happens. Is there a workaround for this? Can we bypass particular connection while waiting?

**Comment by paul-hammant** [comment]
Work around would be to not use `waitForAngularRequestToFinish()`. Instead do one of the more traditional wait-for strategies - https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp or https://github.com/SeleniumHQ/fluent-selenium#within

**Comment by paul-hammant** [comment]
OK, @sarojpurbey324 ?

**Comment by sarojpurbey324** [comment]
As per now We have implemented the traditional wait-for strategies for the Automation. But the traditional waits which we have implemented are not much reliable in our case as waitForAngularRequestToFinish() used to be. So, Is there any alternative for traditional waits which behaves same as  waitForAngularRequestToFinish() ?.

**Comment by paul-hammant** [comment]
` waitForAngularRequestToFinish()` works for most people. I think the strategies I linked to are best. If you're doing `Thread.sleep(10000)` then I'd say look at the links I provided :)

**Comment by sarojpurbey324** [comment]
Ok , I will try that.  Thank You
