### ISSUE TITLE
Cannot read `modelField' of undefined

### ISSUE THREAD

**Issue by opahopa** [paul-hammant/ngWebDriver#80]
Hi,

I'm trying mutate & read the model with `ngWebDriver`.
In both cases getting `Cannot read "modelField" of undefined` error. Tried to play around with `.withRootSelector()`, however it doesn't seem to affect the issue. The `modelField` belongs to the element within a modal -> tried to select the root `ng-app` & a few different selectors for the modal's root. Please advise if i'm doing something wrong. 

```
            NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor)browser);
            // NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor)browser).withRootSelector("[role=dialog]");
            ngWebDriver.waitForAngularRequestsToFinish();

            WebElement elem = browser.findElement(By.xpath("//div[@attr0]"));

            ngWebDriver.mutate(elem, "modelField.value0", "'e32r3r23r23r323t32r32r'");
            logger.info(ngWebDriver.retrieveAsString(elem, "modelField.value0"));

```

selected div (`elem`):
`<div attr0="" ng-model="modelField.value0"></div>`

`WebElement elem` is not `undefined` and contains a valid `WebElement` instance

**Comment by paul-hammant** [comment]
Yeah, I'm going to need something reproducible.

**Comment by paul-hammant** [comment]
Look, I can't help you unless you make this reproducible for me.
