### ISSUE TITLE
What is the import package for using ngWebDriver class ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [paul-hammant/ngWebDriver#81]
I have a dependency in my pom as 

```
<dependency>
            <groupId>com.paulhammant</groupId>
            <artifactId>ngwebdriver</artifactId>
            <version>1.1.4</version>
          <!--  <scope>test</scope> -->
        </dependency>
```

In my code I am using 
```
 NgWebDriver ngdriver;
//Creating an instance of NgWebDriver
  ngdriver = new NgWebDriver((JavascriptExecutor) driver);
```
I used the below import statments.
```
import com.paulhammant.ngwebdriver.NgWebDriver;
import com.paulhammant.ngwebdriver.ByAngular;
```

Still I can not get the ngWebDriver resolved for compilation ? What mistake I am doing ?

**Comment by PrasadNutalapati** [comment]
Compilation error is gone when I commented the "scope" tag from dependency.

```
	<!-- <scope>test</scope> -->
```

**Comment by paul-hammant** [comment]
Here's an example, Prasad - https://github.com/paul-hammant/ngWebDriver/blob/master/src/test/java/com/paulhammant/ngwebdriver/AngularAndWebDriverTest.java

**Comment by paul-hammant** [comment]
I think you're good now, Prasad, right?
