### ISSUE TITLE
@ByAngularBinding.FindBy(...)

### ISSUE THREAD

**Issue by mcmug8** [paul-hammant/ngWebDriver#83]
I am getting unresolvable reference to  'ByAngularBinding.FindBy'. Everything seems setup correctly, got the Maven dependencies. What is wrong is my project? any idea?

**Comment by paul-hammant** [comment]
Make a reproduction for me please.

**Comment by mcmug8** [comment]
Sorry and thank you, I fixed the issue.

**Comment by paul-hammant** [comment]
no probs!
