### ISSUE TITLE
I get WebDriverException: unknown error: angular is not defined and if use waitForAngularRequestsToFinish I get ScriptTimeoutException. 

### ISSUE THREAD

**Issue by psiservices-bshet** [paul-hammant/ngWebDriver#84]

**Comment by paul-hammant** [comment]
Give me a way to wholly reproduce your problem, and I will help you.

**Comment by psiservices-bshet** [comment]
<img width="960" alt="bug" src="https://user-images.githubusercontent.com/45674322/53658613-16b9e100-3c0e-11e9-9622-4e58fdbdda79.png">

ngWebDriver = new NgWebDriver((JavascriptExecutor)driver).withRootSelector("app-root");
         ngWebDriver.waitForAngularRequestsToFinish();
         driver.findElement(ByAngular.binding("expiryDateInput")).sendKeys("102020");
         driver.findElement(ByAngular.cssContainingText("#cvvInput","CVV")).sendKeys("123") 

This above image and code snippet is what I am trying to do but i get error as i mentioned in the issue.  Our application is developed using angular 5. Please let me know if you need any more information.

**Comment by paul-hammant** [comment]
I can't see the element with `app-root` in the screen-shot. I really can't help you unless you make this reproducible for me

**Comment by psiservices-bshet** [comment]
<img width="960" alt="bug2" src="https://user-images.githubusercontent.com/45674322/53755243-e622b300-3e6a-11e9-8c80-371cb3f2de4f.png">

Thanks for your response. I have attached another screenshot. PLease let me know if this helps.

**Comment by paul-hammant** [comment]
Well, `.withRootSelector("app-root")` should work. Try `.withRootSelector(".app-root")` instead, or `.withRootSelector(".wrapper-app-root")`

**Comment by pallavijaini05** [comment]
Hi,

I am newbie to UI testing. We have a portal built on Angular 5 framework. I am trying to use ngWebDriver to ease my UI testing but getting the **org.openqa.selenium.WebDriverException: javascript error: angular is not defined** exception.

My project settings are as below.

As a first step

In maven pom.xml, added the below dependencies

`<dependency>
			<groupId>org.seleniumhq.selenium.fluent</groupId>
			<artifactId>fluent-selenium</artifactId>
			<version>1.20</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>  
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-java</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>[3,)</version>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.jetty.websocket</groupId>
					<artifactId>websocket-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.paulhammant</groupId>
			<artifactId>ngwebdriver</artifactId>
			<version>1.1.4</version>
		</dependency>`

2. Written the test case as below. As first few clicks not much of the angular/text boxes.. most of them are clicks to navigate to correct page, so not used the ByAngular. Trying to use ByAngular for one of the angular2-multiselect element.

`package com.test;

import java.util.concurrent.TimeUnit;

import org.apache.log4j.Logger;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.test.context.junit4.SpringRunner;

import com.paulhammant.ngwebdriver.ByAngular;
import com.paulhammant.ngwebdriver.NgWebDriver;

@RunWith(SpringRunner.class)
public class NgWebDriverTest {
	Logger Log = Logger.getLogger(SeleniumTest.class);
	private WebDriver driver;
	private NgWebDriver ngDriver;

	@Before
	public void setup() {
		System.setProperty("webdriver.chrome.driver",
				"C:\\xxxx\\chromedriver.exe");
	}

	@Test
	public void testTest() throws Exception {
		driver = new ChromeDriver();
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.get("http://localhost:4200/#/welcomePage");

		driver.manage().window().maximize();
		Log.info("URL is launched");

		Thread.sleep(5000);
		Assert.assertTrue(driver.getCurrentUrl().endsWith("welcomePage"));

		driver.findElement(By.xpath("html/body/app-root/app-navbar/nav/div/div[2]/ul/div[2]/div[1]")).click();
		Log.info("'Selfservice' option is clicked");

		driver.findElement(By.xpath("html/body/app-root/app-navbar/nav/div/div[2]/ul/div[2]/div[2]/a[1]")).click();
		Log.info("'Build' option is clicked");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id='MFT']")).click();
	
		driver.findElement(
				By.xpath("html/body/app-root/div/app-landing/div[2]/div[3]/div/div/div/div/div[1]/div/div[2]/h4/a"))
				.click();
		
		Thread.sleep(7000);

		ngDriver = new NgWebDriver((JavascriptExecutor) driver).withRootSelector(".app-account");
		ngDriver.waitForAngularRequestsToFinish();
		
		WebElement e =	 driver.findElement(ByAngular.binding("accountApplication"));
        Log.info("I am here and eleent is: " + e);
	   
		 
	}

}
`
My main problem is Angular itself is not loaded, if it is loaded i can try and make sure it is binding or able to retrieve the values or not.

Any help is greatly appreciated !!

Thanks,
Pallavi Jaini

**Comment by paul-hammant** [comment]
You need to share the HTML as loaded into the browser for me to be able to help.   The maven-dependency section, the fragment of Java don't help me. I need the HTML+body+divs up to an including ".app-account"

Also xoath - //html/body/app-root/app-navbar/nav/div/div[2]/ul/div[2]/div[1] - is NOT the way to code reliable Selenium/WebDriver scripts.

**Comment by pallavijaini05** [comment]
Thank you for your response Paul. I have figured out the above issue as i was not using teh ByAngular correctlty. Now changed my test case to looks like as below.

`driver = new ChromeDriver();
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.get("http://localhost:4200/#/welcomePage");

		driver.manage().window().maximize();
		Log.info("URL is launched");

		Thread.sleep(3000);
		Assert.assertTrue(driver.getCurrentUrl().endsWith("welcomePage"));

		ngDriver = new NgWebDriver((JavascriptExecutor) driver);
		ngDriver.waitForAngularRequestsToFinish();

		driver.findElement(ByAngular.cssContainingText(".nav-link", "Self Services")).click();
		Log.info("Self-service is clicked");

		driver.findElement(ByAngular.cssContainingText(".dropdown-item", "Build")).click();
		Log.info("Build is clicked");
`

Just to mention, i am using Angular 5. Now i am facing an issue while sending the content to my input elements using ByAngular. 

HTML content is 
`<input _ngcontent-c7="" class="form-control ng-pristine ng-valid ng-touched" name="email" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$" type="email" ng-reflect-klass="form-control" ng-reflect-ng-class="[object Object]" ng-reflect-required="false" ng-reflect-pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+" ng-reflect-name="email">`

Java statement used to retrieve 

`WebElement e = driver.findElement(ByAngular.cssContainingText(".form-control",""));
e.sendKeys("test@gmail.com");`

I am receiving the error as org.openqa.selenium.WebDriverException: element not interactable.

Can you please help here.


Thanks,
Pallavi Jaini

**Comment by paul-hammant** [comment]
how about `By.name("email")` ?

**Comment by pallavijaini05** [comment]
It worked. I tried  like below. 

driver.findElement(ByAngularBinding.name("email")).sendKeys("test@gmail.com");

I am all set with my test case. Thanks a lot for your reponse.

**Comment by paul-hammant** [comment]
You're welcome

**Comment by Guruprasadraobk** [comment]
Hi Paul,

Could you please guide me to find "manage-roles" element and then click on that element for an angular application using ngWebDriver

Below is the HTML:

**<a _ngcontent-bkq-c4="" routerlink="manage-roles" ng-reflect-router-link="manage-roles" href="#/home/manage-roles" style="" xpath="1"><i _ngcontent-bkq-c4="" class="icon-roles"></i> Roles</a>**

1) How to deal with "ng-reflect-router-link" and "_ngcontent" elements
2) How to find an element using its text (Similar to that in path)

Your help is really appreciated. Thanks in advance

**Comment by paul-hammant** [comment]
Just use regular WebDriver for that. XPath & attriubtes. ngWebDriver isn't needed for that

**Comment by Guruprasadraobk** [comment]
Thank you Paul.

**Comment by dinaRodeny** [comment]
i have the same issue  an error has occurred :angular is not defined
code :
/* password annotation*/
@ByAngularBinding.FindBy(binding = "password")
//@ByAngularCssContainingText.FindBy(cssSelector = "form-group", searchText = "password")
	@FindBy(how = How.NAME, using = "password")
	WebElement passwordTxtBox;
![ave44](https://user-images.githubusercontent.com/37294950/88463586-a9dd6180-ce68-11ea-87e0-7cbb3d2df870.PNG)
 

![Maven42](https://user-images.githubusercontent.com/37294950/88463563-7ef30d80-ce68-11ea-9fe5-6369283f7115.PNG)

**Comment by paul-hammant** [comment]
You may have to flip to a non annotation way of doing it:

WebDriver wd = .. firefox or chrome ..
WebElement element = wd.findElement(By.xpath("//input[@name='password']"));

**Comment by dinaRodeny** [comment]
![MAven2323](https://user-images.githubusercontent.com/37294950/88464781-5cfe8880-ce72-11ea-95d2-2b883651c9a5.PNG)
it works correclty when i use @FindBy(how = How.NAME, using = "password")
and i want to use  Angular also angular  is working correctly with button but with textfield is not working any help ?! thnx in advance 
![12345](https://user-images.githubusercontent.com/37294950/88464830-b5358a80-ce72-11ea-8306-bb564c681d99.PNG)

**Comment by paul-hammant** [comment]
The HTML you showed me has nothing to do with Angular. Why are you wanting to use ngWebDriver at all?

**Comment by dinaRodeny** [comment]
I wanna handle  HTTP interceptor for the signUp page

**Comment by paul-hammant** [comment]
I can't help if you're being so evasive.

**Comment by paul-hammant** [comment]
Can you direct me to the site in question?

**Comment by agatonovicmara** [comment]
Hi Paul,

I hope you're still available for some questions. 
Whatever I try I cannot grab elements from this page. It's a SPA application and _it drove me crazy._
I incorporated ngWebDriver but still, cannot do anything.
Can you see what's wrong?

My HTML code:
<img width="389" alt="html" src="https://user-images.githubusercontent.com/92210129/182822692-e7cf8ace-8eb8-46b4-8aac-ed5852c2444a.PNG">

**My class (SignInPage)**


import com.paulhammant.ngwebdriver.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;

public class SignInPage {
    private WebDriver driver;
    private NgWebDriver ngDriver;

    public SignInPage(WebDriver driver) {
        this.driver = driver;
    }

    public SignInPage(NgWebDriver ngDriver) {
        this.ngDriver = ngDriver;
    }



    public WebElement getIndividual() {
        return driver.findElement(ByAngular.buttonText("Individual"));


**My test:**

```
   @Test (priority = 30)

    public void chooseAPlan() {

        ngDriver = new NgWebDriver((JavascriptExecutor) driver);
        ngDriver.waitForAngularRequestsToFinish();

        signIn.getIndividual().click();

    }
```

And the error message I get is:

org.openqa.selenium.NoSuchElementException: searchText(Individual) didn't have any matching elements at this place in the DOM

**Comment by ramyaakidi** [comment]
Hi,

**<input _ngcontent-qqj-c10 formcontrolname="username" kendotextbox id="_0e5e3fcf-798e-405d-be8c-08301f4e2db3" class="k-textbox ng-pristine ng-invalid ng-touched">**

can someone help me to find the xpath for the above "username" field.
Whatever I try it is showing exception as unable to find.

Thanks

**Comment by paul-hammant** [comment]
@ramyaakidi - no, not going to help with general selenium questions.

@agatonovicmara will help with an ngWebDriver bug if you can make a new repo that is the smallest possible full reproduction - build file and failing test included.

**Comment by ramyaakidi** [comment]
The question is regarding Angular where Im not able to find the element using any of the Angular Annotations.
Let me know which could help to find the element

**Comment by omgoyal** [comment]
@paul-hammant  
![image](https://user-images.githubusercontent.com/78644715/233284927-bc3df70e-aeee-430c-95bc-75f259c58608.png)

	
	@ByAngularButtonText.FindBy(buttonText ="Apply leave")
	public WebElement ApplyLeave;

org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='Applyleave']"}

Please help me on this...
