### ISSUE TITLE
Not able to retrive text from the <span class="ng-binding" xpath="1">31,504.19</span> just my question how i can use Element Locator i am very new in ngWebDriver

### ISSUE THREAD

**Issue by siddikinvoice** [paul-hammant/ngWebDriver#85]

**Comment by siddikinvoice** [comment]
i don't know which method i need to use to retrive text using ByAngular.

Copy of Element is 👍 **<span class="ng-binding" xpath="1">31,504.19</span>**

1. Relative Xpath: //span[contains(text(),'31,504.19')]
2. Abs Xpath: /html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[3]/banking-overview[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/span[1]
3. CssSelector: div.app-content div.app-body.ng-scope div.padding.ng-scope div.ng-scope banking-overview.ng-scope.ng-isolate-scope div.row.ng-scope div.col-md-6.ng-scope:nth-child(2) div.box div.box-body div.details.two:nth-child(1) div.field:nth-child(2) > span.ng-binding:nth-child(2)

**Comment by paul-hammant** [comment]
Nobody in the Selenium development team thinks long XPaths are a good technique. You should be using ID or css-locators **that are terse and elegant**.  WebDriver also allows driver.findElement(locator).findElement(another locator). You should master those techniques first. Specifically WebDriver techinques **before** ngWebDriver techniques.

I have no idea what you are talking about re "Copy of Element is 👍 31,504.19"

**Comment by siddikinvoice** [comment]
hi paul sorry i mean it copy of Element is 
"<span class="ng-binding" xpath="1">31,504.19</span>"
Actually i want to get "31,504.19" text 
when i use driver.findElement(By.xpath("//span[contains(text(),'31,504.19')]")); i get this text but i dont want to pass  31,504.19 value because 31,504.19 value could be difference that is the my question

**Comment by paul-hammant** [comment]
So that's a shorter XPath, but again it is not good WebDriver practice.  I'd need to see the whole HTML fragment from root in order to be able to help you make the best test code. Can you share that?

**Comment by siddikinvoice** [comment]
No Thanks

**Comment by paul-hammant** [comment]
I can't help you unless you make this reproducible for me.

**Comment by siddikinvoice** [comment]
Thanks a million issue are now resolved my actual issue was Delaying the browser to load the element NOT Element Locator although i am using Webdriver to make browser to wait AngularJS Page to load i was trying to use traditional method to stop Angular JS page load 
final i use the bellow method to delay browser to load the AngularJs Page

public static void untilAngularJSFinish(WebDriver driver) {
		final String javaScriptToLoadAngular = "var injector = window.angular.element('body').injector();"
				+ "var $http = injector.get('$http');" + "return ($http.pendingRequests.length === 0)";

		ExpectedCondition<Boolean> pendingAngularJSLoad = new ExpectedCondition<Boolean>() {
			public Boolean apply(WebDriver driver) {
				return ((JavascriptExecutor) driver).executeScript(javaScriptToLoadAngular).equals(true);
			}
		};
		WebDriverWait wait = new WebDriverWait(driver, 20); // timeout = 20 secs
		wait.until(pendingAngularJSLoad);
	}
