### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by jith-mj** [paul-hammant/ngWebDriver#86]
Hi,

We are starting with test automation for a project where we have many Angular v7 pages. We are considering Selenium with ngWebDriver. 
Is ngWebDriver supports all locators such as binding, modal,repeater, etc with Angular 7?

Thanks,
Jith

**Comment by paul-hammant** [comment]
Yes it does.

**Comment by jith-mj** [comment]
Thanks Paul for response!
