### ISSUE TITLE
Wait for element issue

### ISSUE THREAD

**Issue by Yamuna-Rani** [paul-hammant/ngWebDriver#87]
Hi Paul,

I am using your framework in my testing script for test the angular based applications.

In that, I  am facing some issue in webelement locator.

@ByAngularModel.FindBy(model = "q")
	private WebElement name;
	public void enterText()
	{
		WebHandlers.enterText(name, "Tsting");
	} 

Here name is the webelement but it is showing like unknown locator. so i cant able to use the wait for the element function in selenium.

I am attaching the screenshot regarding this issue. Can you please help me for the same.

[element.docx](https://github.com/paul-hammant/ngWebDriver/files/3749557/element.docx)

**Comment by Yamuna-Rani** [comment]
Hi Paul,

Thank you for your concern :)  I have resolved this issue. You can close the ticket.

Regards,
Yamuna

**Comment by paul-hammant** [comment]
no probs, sir!
