### ISSUE TITLE
what locator for ng webdriver can we use from below code?  <input _ngcontent-c1="" class="size mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-valid ng-touched ng-dirty" matinput="" name="mobile" placeholder="Mobile" id="mat-input-0" aria-invalid="false" aria-required="false">

### ISSUE THREAD

**Issue by mohammadafzal32** [paul-hammant/ngWebDriver#91]
<input _ngcontent-c1="" class="size mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-valid ng-touched ng-dirty" matinput="" name="mobile" placeholder="Mobile" id="mat-input-0" aria-invalid="false" aria-required="false">

**Comment by paul-hammant** [comment]
Use Regular WebDriver's By.id function -> "mat-input-0"
