### ISSUE TITLE
insert ngWebDriver in a browserFactory

### ISSUE THREAD

**Issue by DvorahC** [paul-hammant/ngWebDriver#92]
Hello Paul,

I am QA Automation engineer in charge of setting up the Web Automation for our website.
I set up the system with Java/Selenium/TestNG/Cucumber. I read your documentation but I could not find the answers to my issues. 

I already have a java class returning the driver that I am using for my tests according to the browser I am testing. 
Since part of our website is in Angular I had issues interacting with elements so I am starting to add ngWebDriver.

 But I get several blocking issues:

1. Our website is partially built with Angular....is there a possibility to "detect" before each page if I should use or not ngWebDriver? 
2. if I add ngWebDriver to my BrowserFactory so my getDriver() returns ngWebDriver but then I get this error:
_com.paulhammant.ngwebdriver.NgWebDriver cannot be cast to org.openqa.selenium.WebDriver_
3. if I change all my code to return only ngWebDriver....can this still interact with elements which are not in angular in the website?

Because our website is partially with Angular I cant find the solution online on how to refactor my code so that all elements can be detected.

Thanks a lot for the help!
Dvorah

**Comment by paul-hammant** [comment]
You want to do:

```
NgWebDriver ngWebDriver = new NgWebDriver(existingWebDriverAsPerSetup);
```

Maybe make your own NgWebDriver extension that one-time does a `ngWebDriver.waitForAngularRequestsToFinish();` before each method invoation to make it lazy, and be a good citizen for pages being Angular or not.

**Comment by DvorahC** [comment]
Hello Paul, 
Thanks a lot for the quick answer! It is almost working. 
I added this into my Hooks before launching my tests. 

Still, it seems that I keep on getting this error: 
'$$testability' of undefined'

I read the answers about it and the README to help fix the issue, but what happen if the website does not seem to have a RootSelector? Then if I understand well the driver cannot find the elements? 

Thanks a lot! 
Dvorah

**Comment by paul-hammant** [comment]
If the webpage does not have Angular (does not have an Angular root element), then use regular WebDriver.findElement(..) with ID, CSS, XPATH locators.  If it does have a Angular root elemenet then use those **OR** the ngWebDriver way of work (mix and match).

**Comment by DvorahC** [comment]
ok, very clear! 
Thanks a lot Paul for the quick help! Dvorah

**Comment by paul-hammant** [comment]
have fun :)
