### ISSUE TITLE
Javascript error Angular is not defined while accessing the element on angular 8

### ISSUE THREAD

**Issue by umeshshende** [paul-hammant/ngWebDriver#94]
Accessing the element on angularjs  its working fine but when angular 8 it is throwing **Javascript error angular is not defined** on last line where ngWebDriver has been called . We also tried with withRootSelector("app-root") as HTML used `<app-root></app-root>` 

`		 NgWebDriver ngWebDriver = new NgWebDriver((JavascriptExecutor) webDriver);
			 WebElement elem =  webDriver.findElement(By.id(id));
			 Object obj =  ngWebDriver.retrieve(elem,"companyData");
`

Reactive form is used in angular 8

**Comment by paul-hammant** [comment]
Does this work for you ? https://github.com/paul-hammant/ngWebDriver#waiting-for-angular-to-finish-async-activity

**Comment by umeshshende** [comment]
No.we are doing for the angular 8 now but when we trying to retrieve the object it say angular is not defined .Did you have example for angular 8 using ngWebDriver accessing reactiveform element

**Comment by paul-hammant** [comment]
I'm not sure what you're telling me. Are you saying that `ngWebDriver.waitForAngularRequestsToFinish();` is not to be called for Angular8 webapps?

**Comment by paul-hammant** [comment]
When I check https://github.com/angular/protractor/commits/master/lib/clientsidescripts.js I note that it has not changed in two years, and the version I have copied into ngWebDriver (and released) is the same as the version that ships with Protractor today.

**Comment by bonapat** [comment]
I've got the same issue, If I run the following test code:

`System.setProperty("webdriver.chrome.driver", "chromedriver.exe");`
`WebDriver driver = new ChromeDriver();`
`NgWebDriver ngDriver  = new NgWebDriver((JavascriptExecutor) driver).withRootSelector("[aio-shell]");`
`driver.get("https://angular.io/");`
`ngDriver .waitForAngularRequestsToFinish();`
`ngDriver.getLocationAbsUrl();`

It throws me the error on the last line getting the url:

`javascript error: angular is not defined   (Session info: chrome=87.0.4280.66) Build info: version: '3.141.59'`

Versions:

- selenium 3.141.59
- ngwebdriver 1.1.6
- chromedriver 87.0.4280.20

**Comment by paul-hammant** [comment]
@bonapat What would be the Angular element in that page that you would interact with?

**Comment by bonapat** [comment]
I want to test a customer angular application and I get that particular error. Just wanted to show that it‘s also reproducible on angular.io page.

**Comment by paul-hammant** [comment]
I can't immediately see any Angular widgets that are shown. The sidebar is closed. I don't know what to click on to open the sidebar. When I do a wget to look at the source of the page before JS has kicked in element you're trying to indicate is an Angular root is empty.  I don't know how to help you.

Do you know NodeJS?  Maybe you can point Protractor at the same page, and then show it working as you'd expect. If it doesn't work there and you're sure it should, then you can go ahead and raise it with the Protractor team.
