### ISSUE TITLE
selenium-java version incorrect

### ISSUE THREAD

**Issue by duxbuse** [paul-hammant/ngWebDriver#95]
https://github.com/paul-hammant/ngWebDriver/blob/711ec3862d54959f2d101878d1c8907677a15bd0/pom.xml#L72

This version is being set to `[3.x.x,)` I think a translation script is breaking somewhere as this is causing issues.

Should just be `3.x.x` when I manually edit the pom for ngWebDriver it works nominally

**Comment by paul-hammant** [comment]
Might be worth fixing it specifically to 3.141.59 ahead of the 4 release. Thoughts?

**Comment by duxbuse** [comment]
That would suit me perfect.

**Comment by paul-hammant** [comment]
Updated to 4.3
