### ISSUE TITLE
ngWebDriver is not working with when setting desired capabilities for browsers

### ISSUE THREAD

**Issue by Dexter-Clone** [paul-hammant/ngWebDriver#96]
When using Desired Capabilities, I am getting error as below,

_**symbol:   method chrome()
  location: class org.openqa.selenium.remote.DesiredCapabilities**_

Sample code as below for chrome browser,'
case "chrome":
				capability = DesiredCapabilities.chrome();
				System.setProperty("webdriver.chrome.driver", filePath + "\\setupfiles\\chromedriver.exe");
				if (!(hubip.isEmpty())) {
					RemoteWebDriver driver = new RemoteWebDriver(hubURL, capability);
					setDriver(driver);
				} else {
					WebDriver driver = new ChromeDriver(capability);
					setDriver(driver);
				}
				break;

**Comment by paul-hammant** [comment]
You're going to have to tell me more than that for me to be able to help you. How can I reporduce that?

**Comment by Dexter-Clone** [comment]
Hi Paul,

Appreciate your quick response. While I was debugging more on the issue, I found that DesiredCapabilities are deprecated by selenium itself. My bad I was using it.

Closing this issue as it not relevant now. Cheers.

**Comment by paul-hammant** [comment]
No probs - thans for circling back
